import type {
  Product,
  Category,
  Banner,
  Promotion,
  Review,
  Testimonial,
} from "./types";

export const categories: Category[] = [
  {
    id: "1",
    name: "Phones and Tablets",
    slug: "phones-tablets",
    description: "Latest smartphones and tablets",
    image: "/phones-tablets-category.png",
    icon: "📱",
    productCount: 85,
    subcategories: [
      {
        id: "1-1",
        name: "Smartphones",
        slug: "smartphones",
        description: "Latest smartphones",
        image: "/modern-smartphones.png",
      },
      {
        id: "1-2",
        name: "Tablets",
        slug: "tablets",
        description: "High-performance tablets",
        image: "/various-tablets.png",
      },
      {
        id: "1-3",
        name: "Accessories",
        slug: "phone-accessories",
        description: "Phone and tablet accessories",
        image: "/phone-accessories.png",
      },
    ],
  },
  {
    id: "2",
    name: "Computers",
    slug: "computers",
    description: "Laptops, desktops and computer accessories",
    image: "/computers-category.png",
    icon: "💻",
    productCount: 67,
    subcategories: [
      {
        id: "2-1",
        name: "Laptops",
        slug: "laptops",
        description: "High-performance laptops",
        image: "/various-laptops.png",
      },
      {
        id: "2-2",
        name: "Desktops",
        slug: "desktops",
        description: "Desktop computers",
        image: "/desktop-computers.png",
      },
      {
        id: "2-3",
        name: "Computer Accessories",
        slug: "computer-accessories",
        description: "Keyboards, mice, monitors",
        image: "/computer-accessories.png",
      },
    ],
  },
  {
    id: "3",
    name: "Electronics",
    slug: "electronics",
    description: "Audio, gaming and electronic devices",
    image: "/electronics-category.png",
    icon: "🎧",
    productCount: 92,
    subcategories: [
      {
        id: "3-1",
        name: "Headphones",
        slug: "headphones",
        description: "Premium audio devices",
        image: "/diverse-people-listening-headphones.png",
      },
      {
        id: "3-2",
        name: "Gaming",
        slug: "gaming",
        description: "Gaming consoles and accessories",
        image: "/gaming-devices.png",
      },
      {
        id: "3-3",
        name: "Smart Home",
        slug: "smart-home",
        description: "Smart home devices",
        image: "/smart-home-devices.png",
      },
    ],
  },
  {
    id: "4",
    name: "Fashion",
    slug: "fashion",
    description: "Trendy clothing and accessories",
    image: "/fashion-category.png",
    icon: "👗",
    productCount: 234,
    subcategories: [
      {
        id: "4-1",
        name: "Men's Clothing",
        slug: "mens-clothing",
        description: "Stylish men's wear",
        image: "/mens-clothing-display.png",
      },
      {
        id: "4-2",
        name: "Women's Clothing",
        slug: "womens-clothing",
        description: "Trendy women's fashion",
        image: "/womens-clothing.png",
      },
      {
        id: "4-3",
        name: "Accessories",
        slug: "accessories",
        description: "Fashion accessories",
        image: "/fashion-accessories-collection.png",
      },
    ],
  },
  {
    id: "5",
    name: "Home & Office",
    slug: "home-office",
    description: "Furniture and office supplies",
    image: "/home-office-category.jpg",
    icon: "🏠",
    productCount: 189,
    subcategories: [
      {
        id: "5-1",
        name: "Furniture",
        slug: "furniture",
        description: "Quality furniture pieces",
        image: "/assorted-living-room-furniture.png",
      },
      {
        id: "5-2",
        name: "Office Supplies",
        slug: "office-supplies",
        description: "Essential office items",
        image: "/assorted-office-supplies.png",
      },
      {
        id: "5-3",
        name: "Home Decor",
        slug: "home-decor",
        description: "Beautiful home decorations",
        image: "/cozy-living-room.png",
      },
    ],
  },
  {
    id: "6",
    name: "Health & Beauty",
    slug: "health-beauty",
    description: "Personal care and wellness products",
    image: "/health-beauty-category.jpg",
    icon: "💄",
    productCount: 145,
    subcategories: [
      {
        id: "6-1",
        name: "Skincare",
        slug: "skincare",
        description: "Premium skincare products",
        image: "/skincare-products-display.png",
      },
      {
        id: "6-2",
        name: "Makeup",
        slug: "makeup",
        description: "Quality makeup products",
        image: "/makeup-products-flatlay.png",
      },
      {
        id: "6-3",
        name: "Wellness",
        slug: "wellness",
        description: "Health and wellness items",
        image: "/wellness-products-still-life.png",
      },
    ],
  },
  {
    id: "7",
    name: "Sports & Outdoors",
    slug: "sports-outdoors",
    description: "Sports equipment and outdoor gear",
    image: "/sports-outdoors-category.jpg",
    icon: "⚽",
    productCount: 167,
    subcategories: [
      {
        id: "7-1",
        name: "Fitness Equipment",
        slug: "fitness-equipment",
        description: "Home fitness gear",
        image: "/diverse-fitness-equipment.png",
      },
      {
        id: "7-2",
        name: "Outdoor Gear",
        slug: "outdoor-gear",
        description: "Camping and hiking gear",
        image: "/assorted-outdoor-gear.png",
      },
      {
        id: "7-3",
        name: "Sports Apparel",
        slug: "sports-apparel",
        description: "Athletic clothing",
        image: "/diverse-sports-apparel.png",
      },
    ],
  },
  {
    id: "8",
    name: "Baby Products",
    slug: "baby-products",
    description: "Everything for your little ones",
    image: "/baby-products-category.jpg",
    icon: "👶",
    productCount: 98,
    subcategories: [
      {
        id: "8-1",
        name: "Baby Clothing",
        slug: "baby-clothing",
        description: "Comfortable baby clothes",
        image: "/baby-clothing.jpg",
      },
      {
        id: "8-2",
        name: "Baby Gear",
        slug: "baby-gear",
        description: "Essential baby equipment",
        image: "/baby-gear.jpg",
      },
      {
        id: "8-3",
        name: "Toys",
        slug: "toys",
        description: "Educational and fun toys",
        image: "/colorful-baby-toys.png",
      },
    ],
  },
];

export const products: Product[] = [
  {
    id: "1",
    name: "Samsung Galaxy Z Fold 6 Case With S Pen Holder & Stylus, Hard PC Shockproof Protective Cover For Galaxy Z Fold6 5G",
    description:
      "This case is only suitable for Samsung Galaxy Z Fold 6 and is not compatible with other models.",
    price: 550000,
    originalPrice: 850000,
    images: [
      "/phones_and_tablets/galaxyfold.jpg",
      "/phones_and_tablets/galaxyfold2.jpg",
      "/phones_and_tablets/galaxyfold3.jpg",
    ],
    category: "Phones and Tablets",
    subcategory: "Smartphones",
    brand: "Samsung",
    stock: 6,
    rating: 4.8,
    reviewCount: 342,
    featured: true,
    tags: ["smartphone", "samsung", "premium", "latest"],
    specifications: {
      SKU: "SA948EA3ICKJ1NAFAMZ",
      Weight: "0.03kg",
      Color: "Black",
      Main_Material: "Leather",
    },
    variations: [
      {
        id: "1-128",
        name: "Fold 5",
        price: 480000,
        originalPrice: 850000,
        stock: 5,
      },
      {
        id: "1-256",
        name: "Fold 6",
        price: 550000,
        originalPrice: 850000,
        stock: 2,
      },
    ],
    mainFeatures: [
      "100% fashionable and durable. Offering a sophisticated look and great feel.",
      ".Corner bumpers protection for drops. Soft materials offer maximum protection from bumps and hard-hits for the back and sides of your phone.",
      "All buttons and corners are elevated, and raised edges lift the screen and camera lens off the surface.",
      "Keep your phone in like-new condition well and preserves its looks and features, to protect your phone hurt from scratches and gives you mobile phone a special look.",
    ],
    keyFeatures: [
      "This case is only suitable for Samsung Galaxy Z Fold 6 and is not compatible with other models.",
      "Precise Cutouts: Wide cutouts and responsive press keys, as well as easy access to all ports, buttons, cameras, speakers, and mics.",
      "Stable & Durable – Raised beveled edge keeps your touchscreen safe, dust protection, scratch protection and drop protection.",
      "A comprehensive new upgraded anti-fall protective cover with novel and fashionable appearance.",
      "Keeps your device thin and form fitting to fit right in your pocket and bag. This fantastic cases gives your phone a fresh look, and it could be a perfect gift.",
    ],
    whatsInTheBox: [
      "Cover",
      "Pen",
    ],
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-20T14:30:00Z",
  },
  {
    id: "7",
    name: "Samsung Tab A9 Folio Slim Lightweight Tablet Case",
    description: "Premium Android smartphone with S Pen and AI features",
    price: 145000,
    originalPrice: 250000,
    images: [
      "/phones_and_tablets/galaxycase.jpg",
      "/phones_and_tablets/galaxycase2.jpg",
      "/phones_and_tablets/galaxycase3.jpg",
    ],
    category: "Phones and Tablets",
    subcategory: "Smartphones",
    brand: "Samsung",
    stock: 5,
    rating: 4.7,
    reviewCount: 289,
    featured: true,
    tags: ["smartphone", "samsung", "android", "phonecase"],
    specifications: {
      SKU: "SA948EA3P8WFQNAFAMZ",
      Weight : "0.05kg",
      Color: "Black",
    },
    variations: [
      {
        id: "7-256",
        name: "A7 Lite",
        price: 95000,
        originalPrice: 250000,
        stock: 10,
      },
      {
        id: "7-512",
        name: "A9",
        price: 145000,
        originalPrice: 250000,
        stock: 18,
      },
      {
        id: "7-1tb",
        name: "A9 Plus",
        price: 155000,
        originalPrice: 250000,
        stock: 2,
      },
    ],
    mainFeatures: [
      "Built-in smart cover auto on/auto sleep function.",
      "Compact, elegant, stylish, easy to install and remove.",
      "Convenient position for watching movies or writing.",
      "100% high quality, customized and fits your tablet perfectly.",
      "Against unwanted bumps, accidental drops, scratches, bruises or stains.",
      "Package includes one (1) protective case.",
    ],
    keyFeatures: [
      "Protective.",
      "Black.",
      "Flip.",
      "Both sides covered.",
    ],
    whatsInTheBox: [
      "Phone Case",
    ],
    createdAt: "2024-01-12T09:30:00Z",
    updatedAt: "2024-01-22T11:15:00Z",
  },
  {
    id: "8",
    name: "iPad Pro 12.9-inch",
    description:
      "Professional tablet with M2 chip and Liquid Retina XDR display",
    price: 899,
    originalPrice: 999,
    images: [
      "/ipad-pro-12-9.png",
      "/ipad-pro-keyboard.png",
      "/ipad-pro-pencil.png",
    ],
    category: "Phones and Tablets",
    subcategory: "Tablets",
    brand: "Apple",
    stock: 18,
    rating: 4.9,
    reviewCount: 156,
    featured: true,
    tags: ["tablet", "apple", "professional", "m2"],
    specifications: {
      Display: "12.9-inch Liquid Retina XDR",
      Chip: "Apple M2",
      Storage: "128GB",
      Camera: "12MP Wide + 10MP Ultra Wide",
    },
    variations: [
      {
        id: "8-128",
        name: "128GB Wi-Fi",
        price: 899,
        originalPrice: 999,
        stock: 18,
        sku: "IPADPRO-128W",
      },
      {
        id: "8-256",
        name: "256GB Wi-Fi",
        price: 1099,
        originalPrice: 1199,
        stock: 14,
        sku: "IPADPRO-256W",
      },
      {
        id: "8-512",
        name: "512GB Wi-Fi",
        price: 1299,
        originalPrice: 1399,
        stock: 8,
        sku: "IPADPRO-512W",
      },
      {
        id: "8-128c",
        name: "128GB Cellular",
        price: 1099,
        originalPrice: 1199,
        stock: 12,
        sku: "IPADPRO-128C",
      },
    ],
    mainFeatures: [
      "M2 chip delivers incredible performance for demanding workflows",
      "12.9-inch Liquid Retina XDR display with ProMotion technology",
      "Pro camera system with LiDAR Scanner for AR experiences",
      "All-day battery life up to 10 hours of surfing the web",
      "Compatible with Apple Pencil (2nd generation) and Magic Keyboard",
    ],
    keyFeatures: [
      "iPadOS with desktop-class apps and multitasking",
      "Thunderbolt / USB 4 port for fast connectivity",
      "Face ID for secure authentication and Apple Pay",
      "Four-speaker audio system with spatial audio",
      "5G cellular option for connectivity anywhere",
      "Center Stage camera keeps you in frame during video calls",
    ],
    whatsInTheBox: [
      "iPad Pro",
      "USB-C Charge Cable (1 meter)",
      "20W USB-C Power Adapter",
      "Documentation",
    ],
    createdAt: "2024-01-10T14:20:00Z",
    updatedAt: "2024-01-25T16:45:00Z",
  },
  {
    id: "9",
    name: "Samsung Galaxy Z Fold 6 Case",
    description: "Hard PC Shockproof Protective Cover with S Pen Holder",
    price: 480000,
    originalPrice: 550000,
    images: [
      "/phones_and_tablets/galaxycase.jpg",
      "/phones_and_tablets/galaxycase2.jpg",
      "/phones_and_tablets/galaxycase3.jpg",
    ],
    category: "Phones and Tablets",
    subcategory: "Accessories",
    brand: "Samsung",
    stock: 45,
    rating: 4.5,
    reviewCount: 78,
    featured: false,
    tags: ["case", "samsung", "fold", "protection"],
    specifications: {
      SKU: "SA948EA3ICKJ1NAFAMZ",
      Weight: "0.03kg",
      Color: "Black",
      "Main Material": "Leather",
    },
    variations: [
      {
        id: "9-fold5",
        name: "Fold 5",
        price: 480000,
        originalPrice: 550000,
        stock: 25,
        sku: "SGZF5-CASE",
      },
      {
        id: "9-fold6",
        name: "Fold 6",
        price: 520000,
        originalPrice: 580000,
        stock: 20,
        sku: "SGZF6-CASE",
      },
    ],
    mainFeatures: [
      "Delicate Touch creates a subtle and luxurious texture",
      "Hard PC material provides superior drop protection",
      "Built-in S Pen holder keeps your stylus secure and accessible",
      "Precise cutouts for easy access to all ports and buttons",
      "Slim profile maintains the phone's elegant design",
    ],
    keyFeatures: [
      "This case is only suitable for Samsung Galaxy Z Fold 6 and is not compatible with other models",
      "Precise Cutouts: Wide cutouts and responsive press keys, as well as easy access to all ports, buttons, cameras, speakers, and mics",
      "Stable & Durable – Raised beveled edge keeps your touchscreen safe, dust protection, scratch protection and drop protection",
      "A comprehensive new upgraded anti-fall protective cover with novel and fashionable appearance",
      "Keeps your device thin and form fitting to fit right in your pocket and bag. This fantastic cases gives your phone a fresh look, and it could be a perfect gift",
    ],
    whatsInTheBox: ["Protective Case", "S Pen Holder", "Installation Guide"],
    createdAt: "2024-01-08T11:00:00Z",
    updatedAt: "2024-01-20T13:30:00Z",
  },
  {
    id: "2",
    name: 'MacBook Pro 16"',
    description: "Powerful laptop with M3 Pro chip for professional workflows",
    price: 2499,
    images: [
      "/macbook-pro-16-inch.jpg",
      "/macbook-pro-keyboard.jpg",
      "/macbook-pro-ports.jpg",
    ],
    category: "Computers",
    subcategory: "Laptops",
    brand: "Apple",
    stock: 15,
    rating: 4.9,
    reviewCount: 128,
    featured: true,
    tags: ["laptop", "apple", "professional", "M3"],
    specifications: {
      Display: "16.2-inch Liquid Retina XDR",
      Chip: "Apple M3 Pro",
      Memory: "18GB Unified Memory",
      Storage: "512GB SSD",
    },
    variations: [
      {
        id: "2-m3pro",
        name: "M3 Pro 18GB/512GB",
        price: 2499,
        stock: 15,
        sku: "MBP16-M3P-512",
      },
      {
        id: "2-m3pro-1tb",
        name: "M3 Pro 18GB/1TB",
        price: 2899,
        stock: 8,
        sku: "MBP16-M3P-1TB",
      },
      {
        id: "2-m3max",
        name: "M3 Max 36GB/1TB",
        price: 3499,
        stock: 5,
        sku: "MBP16-M3M-1TB",
      },
    ],
    mainFeatures: [
      "M3 Pro chip with up to 12-core CPU and 18-core GPU for incredible performance",
      "16.2-inch Liquid Retina XDR display with 1000 nits sustained brightness",
      "Up to 22 hours of battery life for all-day productivity",
      "Advanced camera and audio for crystal-clear video calls",
      "Extensive connectivity with Thunderbolt 4, HDMI, and MagSafe 3",
    ],
    keyFeatures: [
      "macOS Sonoma with powerful productivity features",
      "Studio-quality three-mic array with directional beamforming",
      "Six-speaker sound system with force-cancelling woofers",
      "1080p FaceTime HD camera with advanced image signal processor",
      "Magic Keyboard with Touch ID for secure unlock and payments",
      "Force Touch trackpad for precise cursor control",
    ],
    whatsInTheBox: [
      "16-inch MacBook Pro",
      "140W USB-C Power Adapter",
      "USB-C to MagSafe 3 Cable (2 m)",
      "Documentation",
    ],
    createdAt: "2024-01-10T09:00:00Z",
    updatedAt: "2024-01-18T16:45:00Z",
  },
  {
    id: "10",
    name: "Dell XPS 13 Plus",
    description: "Ultra-thin laptop with 12th Gen Intel processors",
    price: 1299,
    originalPrice: 1499,
    images: [
      "/dell-xps-13-plus.png",
      "/dell-xps-keyboard.png",
      "/dell-xps-ports.png",
    ],
    category: "Computers",
    subcategory: "Laptops",
    brand: "Dell",
    stock: 22,
    rating: 4.6,
    reviewCount: 94,
    featured: false,
    tags: ["laptop", "dell", "ultrabook", "intel"],
    specifications: {
      Display: "13.4-inch InfinityEdge",
      Processor: "Intel Core i7-1260P",
      Memory: "16GB LPDDR5",
      Storage: "512GB SSD",
    },
    variations: [
      {
        id: "10-i5",
        name: "i5/8GB/256GB",
        price: 999,
        originalPrice: 1199,
        stock: 18,
        sku: "XPS13P-I5-256",
      },
      {
        id: "10-i7",
        name: "i7/16GB/512GB",
        price: 1299,
        originalPrice: 1499,
        stock: 22,
        sku: "XPS13P-I7-512",
      },
      {
        id: "10-i7-1tb",
        name: "i7/32GB/1TB",
        price: 1699,
        originalPrice: 1899,
        stock: 12,
        sku: "XPS13P-I7-1TB",
      },
    ],
    mainFeatures: [
      "12th Gen Intel Core processors for exceptional performance",
      "13.4-inch InfinityEdge display with minimal bezels",
      "Premium aluminum and carbon fiber construction",
      "Capacitive function row replaces traditional function keys",
      "Ultra-portable design at just 2.73 lbs",
    ],
    keyFeatures: [
      "Windows 11 Home with enhanced productivity features",
      "Up to 12 hours of battery life",
      "Thunderbolt 4 ports for versatile connectivity",
      "Precision touchpad with Windows precision drivers",
      "Killer Wi-Fi 6E for fast wireless connectivity",
      "Waves MaxxAudio Pro for immersive sound",
    ],
    whatsInTheBox: [
      "Dell XPS 13 Plus",
      "65W USB-C Power Adapter",
      "USB-C to USB-A Adapter",
      "Documentation",
    ],
    createdAt: "2024-01-14T10:30:00Z",
    updatedAt: "2024-01-24T14:20:00Z",
  },
  {
    id: "11",
    name: "Gaming Desktop PC",
    description: "High-performance gaming desktop with RTX 4070",
    price: 1899,
    originalPrice: 2199,
    images: [
      "/gaming-desktop-pc.png",
      "/gaming-pc-interior.png",
      "/gaming-pc-rgb.png",
    ],
    category: "Computers",
    subcategory: "Desktops",
    brand: "Custom Build",
    stock: 8,
    rating: 4.8,
    reviewCount: 67,
    featured: true,
    tags: ["desktop", "gaming", "rtx", "high-performance"],
    specifications: {
      Processor: "AMD Ryzen 7 7700X",
      Graphics: "NVIDIA RTX 4070",
      Memory: "32GB DDR5",
      Storage: "1TB NVMe SSD",
    },
    variations: [
      {
        id: "11-rtx4070",
        name: "RTX 4070",
        price: 1899,
        stock: 8,
        sku: "GAMINGPC-RTX4070",
      },
      {
        id: "11-rtx4090",
        name: "RTX 4090",
        price: 2299,
        stock: 5,
        sku: "GAMINGPC-RTX4090",
      },
    ],
    mainFeatures: [
      "High-performance AMD Ryzen 7 7700X processor",
      "NVIDIA RTX 4070 graphics card for stunning visuals",
      "32GB DDR5 RAM for smooth multitasking",
      "1TB NVMe SSD for fast data access",
      "Compact design for easy setup and storage",
    ],
    keyFeatures: [
      "Windows 11 Pro for gaming and productivity",
      "8-core processor for demanding tasks",
      "16GB RAM upgrade option",
      "RGB lighting for customizable aesthetics",
      "Multiple USB ports for connectivity",
      "Built-in Wi-Fi 6 for fast internet speeds",
    ],
    whatsInTheBox: [
      "Gaming Desktop PC",
      "NVIDIA RTX 4070 Graphics Card",
      "AMD Ryzen 7 7700X Processor",
      "32GB DDR5 RAM",
      "1TB NVMe SSD",
      "Power Supply",
      "Operating System",
      "Documentation",
    ],
    createdAt: "2024-01-16T12:00:00Z",
    updatedAt: "2024-01-26T15:30:00Z",
  },
  {
    id: "12",
    name: "Mechanical Gaming Keyboard",
    description: "RGB backlit mechanical keyboard with Cherry MX switches",
    price: 149,
    originalPrice: 199,
    images: [
      "/mechanical-keyboard.png",
      "/keyboard-rgb.png",
      "/keyboard-switches.png",
    ],
    category: "Computers",
    subcategory: "Computer Accessories",
    brand: "Corsair",
    stock: 56,
    rating: 4.7,
    reviewCount: 234,
    featured: false,
    tags: ["keyboard", "mechanical", "gaming", "rgb"],
    specifications: {
      Switches: "Cherry MX Red",
      Backlight: "RGB",
      Connection: "USB-C",
      Layout: "Full Size",
    },
    variations: [
      {
        id: "12-red",
        name: "Red",
        price: 149,
        stock: 56,
        sku: "CORSAIR-MK-RED",
      },
      {
        id: "12-blue",
        name: "Blue",
        price: 149,
        stock: 48,
        sku: "CORSAIR-MK-BLUE",
      },
    ],
    mainFeatures: [
      "RGB backlit keys for customizable lighting",
      "Cherry MX Red switches for tactile feedback",
      "USB-C connection for easy setup",
      "Full-size layout for comfortable typing",
      "Anti-ghosting for accurate key presses",
    ],
    keyFeatures: [
      "100% anti-ghosting keys",
      "N-key rollover for smooth typing",
      "Adjustable keycaps for personalized feel",
      "Water-resistant design for durability",
      "Compact size for easy storage",
      "Built-in USB hub for additional connectivity",
    ],
    whatsInTheBox: ["Mechanical Gaming Keyboard", "USB-C Cable", "User Manual"],
    createdAt: "2024-01-11T08:45:00Z",
    updatedAt: "2024-01-21T10:15:00Z",
  },
  {
    id: "3",
    name: "Sony WH-1000XM5",
    description: "Industry-leading noise canceling wireless headphones",
    price: 399,
    originalPrice: 449,
    images: [
      "/sony-wh-1000xm5.png",
      "/sony-headphones-side-view.jpg",
      "/sony-headphones-case.jpg",
    ],
    category: "Electronics",
    subcategory: "Headphones",
    brand: "Sony",
    stock: 42,
    rating: 4.7,
    reviewCount: 256,
    featured: true,
    tags: ["headphones", "wireless", "noise-canceling", "premium"],
    specifications: {
      Driver: "30mm",
      "Battery Life": "30 hours",
      Connectivity: "Bluetooth 5.2",
      Weight: "250g",
    },
    variations: [
      {
        id: "3-std",
        name: "Standard",
        price: 399,
        stock: 42,
        sku: "WH1000XM5-STD",
      },
      { id: "3-pro", name: "Pro", price: 449, stock: 35, sku: "WH1000XM5-PRO" },
    ],
    mainFeatures: [
      "Industry-leading noise cancellation technology",
      "30mm driver unit for clear sound",
      "Bluetooth 5.2 connectivity for seamless pairing",
      "30-hour battery life for all-day use",
      "Comfortable ear cups for extended wear",
    ],
    keyFeatures: [
      "Transparency Control feature for situational awareness",
      "Adaptive Sound Control for personalized audio experience",
      "Touch controls for easy operation",
      "Water and sweat-resistant design",
      "Lightweight and portable",
      "Built-in microphone for crystal-clear calls",
    ],
    whatsInTheBox: [
      "Sony WH-1000XM5 Headphones",
      "USB-C Charging Cable",
      "Quick Start Guide",
    ],
    createdAt: "2024-01-12T11:30:00Z",
    updatedAt: "2024-01-22T13:15:00Z",
  },
  {
    id: "13",
    name: "PlayStation 5",
    description: "Next-generation gaming console with ultra-high speed SSD",
    price: 499,
    images: ["/playstation-5.png", "/ps5-controller.png", "/ps5-games.png"],
    category: "Electronics",
    subcategory: "Gaming",
    brand: "Sony",
    stock: 12,
    rating: 4.9,
    reviewCount: 445,
    featured: true,
    tags: ["gaming", "console", "playstation", "next-gen"],
    specifications: {
      CPU: "AMD Zen 2",
      GPU: "AMD RDNA 2",
      Storage: "825GB SSD",
      "4K Gaming": "Yes",
    },
    variations: [
      { id: "13-std", name: "Standard", price: 499, stock: 12, sku: "PS5-STD" },
      {
        id: "13-digital",
        name: "Digital Edition",
        price: 449,
        stock: 10,
        sku: "PS5-DIGITAL",
      },
    ],
    mainFeatures: [
      "Next-generation AMD Zen 2 CPU for lightning-fast performance",
      "Ultra-high speed SSD for instant game loading",
      "4K gaming support for stunning visuals",
      "DualSense wireless controller with adaptive triggers",
      "Backward compatible with PlayStation 4 games",
    ],
    keyFeatures: [
      "Sony's Tempest 3D Audio for immersive sound",
      "Ray Tracing support for realistic graphics",
      "3D Audio support for immersive sound",
      "Smart Delivery for automatic game updates",
      "Over 500 games available",
      "Built-in 4K Blu-ray player",
    ],
    whatsInTheBox: [
      "PlayStation 5 Console",
      "DualSense Wireless Controller",
      "Power Supply",
      "Wired Remote Play Adapter",
      "Quick Start Guide",
    ],
    createdAt: "2024-01-09T16:20:00Z",
    updatedAt: "2024-01-19T18:45:00Z",
  },
  {
    id: "14",
    name: "Amazon Echo Dot (5th Gen)",
    description: "Smart speaker with Alexa voice control",
    price: 49,
    originalPrice: 59,
    images: [
      "/echo-dot-5th-gen.png",
      "/echo-dot-colors.png",
      "/echo-dot-setup.png",
    ],
    category: "Electronics",
    subcategory: "Smart Home",
    brand: "Amazon",
    stock: 89,
    rating: 4.4,
    reviewCount: 1234,
    featured: false,
    tags: ["smart-speaker", "alexa", "voice-control", "smart-home"],
    specifications: {
      Speaker: "1.73-inch driver",
      Connectivity: "Wi-Fi, Bluetooth",
      "Voice Control": "Alexa",
      Dimensions: "3.9 x 3.9 x 3.5 inches",
    },
    variations: [
      {
        id: "14-white",
        name: "White",
        price: 49,
        stock: 89,
        sku: "ECHO-DOT-WHITE",
      },
      {
        id: "14-charcoal",
        name: "Charcoal",
        price: 49,
        stock: 75,
        sku: "ECHO-DOT-CHARCOAL",
      },
    ],
    mainFeatures: [
      "Alexa voice control for hands-free convenience",
      "1.73-inch speaker for clear sound",
      "Wi-Fi and Bluetooth connectivity for seamless integration",
      "Compact design for easy placement",
      "Built-in microphone for voice commands",
    ],
    keyFeatures: [
      "Alexa Skills for endless functionality",
      "Smart Home Control for managing devices",
      "Alexa Calling for free phone calls",
      "Alexa Music for streaming your favorite tunes",
      "Alexa Drop In for video calls",
      "Alexa Voice Shopping for easy online purchases",
    ],
    whatsInTheBox: ["Amazon Echo Dot", "Power Supply", "Quick Start Guide"],
    createdAt: "2024-01-13T09:15:00Z",
    updatedAt: "2024-01-23T11:30:00Z",
  },
  {
    id: "15",
    name: "AirPods Pro (2nd Generation)",
    description: "Wireless earbuds with active noise cancellation",
    price: 249,
    originalPrice: 279,
    images: [
      "/airpods-pro-2nd-gen.png",
      "/airpods-case.png",
      "/airpods-ear-tips.png",
    ],
    category: "Electronics",
    subcategory: "Headphones",
    brand: "Apple",
    stock: 67,
    rating: 4.8,
    reviewCount: 892,
    featured: true,
    tags: ["earbuds", "wireless", "noise-canceling", "apple"],
    specifications: {
      Chip: "Apple H2",
      "Battery Life": "6 hours + 24 hours with case",
      "Water Resistance": "IPX4",
      "Noise Cancellation": "Active",
    },
    variations: [
      {
        id: "15-std",
        name: "Standard",
        price: 249,
        stock: 67,
        sku: "AIRPODSPRO-STD",
      },
      {
        id: "15-pro",
        name: "Pro",
        price: 279,
        stock: 58,
        sku: "AIRPODSPRO-PRO",
      },
    ],
    mainFeatures: [
      "Active noise cancellation for immersive listening",
      "Transparency mode for situational awareness",
      "Adaptive EQ for personalized sound",
      "Touch controls for easy operation",
      "Water and sweat-resistant design",
    ],
    keyFeatures: [
      "Spatial audio for 3D sound experience",
      "Force-sensing ear tips for secure fit",
      "Multiple ear tip sizes for comfortable wear",
      "Built-in microphone for crystal-clear calls",
      "Long battery life with charging case",
      "IPX4 water resistance",
    ],
    whatsInTheBox: [
      "AirPods Pro",
      "Charging Case",
      "Ear Tips",
      "Quick Start Guide",
    ],
    createdAt: "2024-01-07T14:45:00Z",
    updatedAt: "2024-01-17T16:20:00Z",
  },
  {
    id: "4",
    name: "Premium Cotton T-Shirt",
    description: "Soft, comfortable cotton t-shirt perfect for everyday wear",
    price: 29,
    images: [
      "/premium-cotton-t-shirt.png",
      "/t-shirt-back-view.png",
      "/t-shirt-fabric-detail.jpg",
    ],
    category: "Fashion",
    subcategory: "Men's Clothing",
    brand: "ComfortWear",
    stock: 156,
    rating: 4.5,
    reviewCount: 89,
    featured: false,
    tags: ["t-shirt", "cotton", "casual", "comfortable"],
    specifications: {
      Material: "100% Organic Cotton",
      Fit: "Regular",
      Care: "Machine Washable",
      Origin: "Made in USA",
    },
    variations: [
      {
        id: "4-regular",
        name: "Regular",
        price: 29,
        stock: 156,
        sku: "COTTONTSHIRT-REG",
      },
      {
        id: "4-large",
        name: "Large",
        price: 29,
        stock: 120,
        sku: "COTTONTSHIRT-LRG",
      },
    ],
    mainFeatures: [
      "100% Organic Cotton for softness and comfort",
      "Regular fit for a classic look",
      "Machine washable for easy care",
      "Made in the USA for quality craftsmanship",
      "Available in multiple sizes",
    ],
    keyFeatures: [
      "Soft and breathable fabric",
      "Comfortable fit for all-day wear",
      "Available in various colors",
      "Ideal for casual outings and daily use",
      "Eco-friendly organic material",
      "Durable construction for long-lasting wear",
    ],
    whatsInTheBox: ["Premium Cotton T-Shirt", "Care Instructions"],
    createdAt: "2024-01-08T14:20:00Z",
    updatedAt: "2024-01-19T10:30:00Z",
  },
  {
    id: "16",
    name: "Designer Leather Handbag",
    description: "Elegant leather handbag perfect for professional settings",
    price: 299,
    originalPrice: 399,
    images: [
      "/leather-handbag.png",
      "/handbag-interior.png",
      "/handbag-details.png",
    ],
    category: "Fashion",
    subcategory: "Accessories",
    brand: "LuxeStyle",
    stock: 23,
    rating: 4.6,
    reviewCount: 145,
    featured: true,
    tags: ["handbag", "leather", "designer", "professional"],
    specifications: {
      Material: "Genuine Leather",
      Dimensions: "12 x 8 x 4 inches",
      Closure: "Magnetic Snap",
      Pockets: "3 Interior, 1 Exterior",
    },
    variations: [
      {
        id: "16-black",
        name: "Black",
        price: 299,
        stock: 23,
        sku: "LEATHERBAG-BLACK",
      },
      {
        id: "16-brown",
        name: "Brown",
        price: 299,
        stock: 20,
        sku: "LEATHERBAG-BROWN",
      },
    ],
    mainFeatures: [
      "Genuine leather construction for durability and elegance",
      "Magnetic snap closure for easy access",
      "3 interior pockets for organization",
      "1 exterior pocket for quick access",
      "Available in multiple colors",
    ],
    keyFeatures: [
      "Water-resistant design for protection",
      "Compact size for easy carrying",
      "Ideal for professional settings",
      "Stylish and fashionable appearance",
      "Built-in RFID protection for added security",
      "Available in various sizes",
    ],
    whatsInTheBox: [
      "Designer Leather Handbag",
      "Cleaning Cloth",
      "User Manual",
    ],
    createdAt: "2024-01-06T13:30:00Z",
    updatedAt: "2024-01-16T15:45:00Z",
  },
  {
    id: "5",
    name: "Ergonomic Office Chair",
    description:
      "Professional office chair with lumbar support and adjustable height",
    price: 299,
    originalPrice: 399,
    images: [
      "/ergonomic-office-chair.png",
      "/office-chair-side-view.png",
      "/office-chair-back-support.jpg",
    ],
    category: "Home & Office",
    subcategory: "Furniture",
    brand: "ErgoMax",
    stock: 28,
    rating: 4.6,
    reviewCount: 167,
    featured: true,
    tags: ["office chair", "ergonomic", "adjustable", "professional"],
    specifications: {
      Material: "Mesh Back, Fabric Seat",
      "Weight Capacity": "300 lbs",
      Adjustments: "Height, Armrests, Lumbar",
      Warranty: "5 Years",
    },
    variations: [
      {
        id: "5-standard",
        name: "Standard",
        price: 299,
        stock: 28,
        sku: "ERGOMAX-STD",
      },
      {
        id: "5-leather",
        name: "Leather",
        price: 349,
        stock: 25,
        sku: "ERGOMAX-LEATHER",
      },
    ],
    mainFeatures: [
      "Mesh back for breathability and comfort",
      "Fabric seat for durability",
      "Adjustable height for personalized fit",
      "Lumbar support for spinal health",
      "Available in multiple colors",
    ],
    keyFeatures: [
      "5-year warranty for peace of mind",
      "Adjustable armrests for added support",
      "Built-in tilt mechanism for easy reclining",
      "Available in various sizes",
      "Ideal for long hours of work",
      "Stylish and professional appearance",
    ],
    whatsInTheBox: [
      "Ergonomic Office Chair",
      "Adjustment Tools",
      "User Manual",
    ],
    createdAt: "2024-01-05T16:45:00Z",
    updatedAt: "2024-01-21T12:00:00Z",
  },
  {
    id: "17",
    name: "Standing Desk Converter",
    description: "Adjustable standing desk converter for healthier work",
    price: 199,
    originalPrice: 249,
    images: [
      "/standing-desk-converter.png",
      "/desk-converter-raised.png",
      "/desk-converter-setup.png",
    ],
    category: "Home & Office",
    subcategory: "Furniture",
    brand: "FlexiDesk",
    stock: 34,
    rating: 4.5,
    reviewCount: 98,
    featured: false,
    tags: ["standing-desk", "adjustable", "ergonomic", "health"],
    specifications: {
      "Height Range": "4.7 - 19.7 inches",
      "Weight Capacity": "35 lbs",
      "Keyboard Tray": "Included",
      Assembly: "No tools required",
    },
    variations: [
      {
        id: "17-standard",
        name: "Standard",
        price: 199,
        stock: 34,
        sku: "FLEXIDESK-STD",
      },
      {
        id: "17-pro",
        name: "Pro",
        price: 249,
        stock: 30,
        sku: "FLEXIDESK-PRO",
      },
    ],
    mainFeatures: [
      "Adjustable height for standing or sitting",
      "Keyboard tray for ergonomic setup",
      "No tools required for assembly",
      "Compact design for easy storage",
      "Available in multiple colors",
    ],
    keyFeatures: [
      "Ideal for promoting healthier work habits",
      "Adjustable height range for personalized fit",
      "Built-in cable management for a tidy workspace",
      "Available in various sizes",
      "Stylish and modern appearance",
      "Easy to install and use",
    ],
    whatsInTheBox: [
      "Standing Desk Converter",
      "Adjustment Tools",
      "User Manual",
    ],
    createdAt: "2024-01-04T11:20:00Z",
    updatedAt: "2024-01-14T13:40:00Z",
  },
  {
    id: "6",
    name: "Vitamin C Serum",
    description:
      "Brightening vitamin C serum for radiant, healthy-looking skin",
    price: 45,
    images: [
      "/vitamin-c-serum-bottle.jpg",
      "/skincare-serum-dropper.png",
      "/vitamin-c-serum-texture.jpg",
    ],
    category: "Health & Beauty",
    subcategory: "Skincare",
    brand: "GlowSkin",
    stock: 73,
    rating: 4.4,
    reviewCount: 203,
    featured: false,
    tags: ["skincare", "vitamin-c", "serum", "brightening"],
    specifications: {
      Concentration: "20% Vitamin C",
      Volume: "30ml",
      "Skin Type": "All Skin Types",
      "Cruelty Free": "Yes",
    },
    variations: [
      { id: "6-30ml", name: "30ml", price: 45, stock: 73, sku: "VITAMINC30ML" },
      { id: "6-60ml", name: "60ml", price: 89, stock: 60, sku: "VITAMINC60ML" },
    ],
    mainFeatures: [
      "20% Vitamin C concentration for powerful brightening",
      "30ml volume for long-lasting use",
      "Suitable for all skin types",
      "Cruelty-free formula",
      "Available in multiple sizes",
    ],
    keyFeatures: [
      "Hydrating formula for nourished skin",
      "Anti-aging properties for youthful appearance",
      "Suitable for daily use",
      "Available in various fragrances",
      "Ideal for sensitive skin",
      "Non-comedogenic formula",
    ],
    whatsInTheBox: ["Vitamin C Serum", "Applicator Dropper", "User Manual"],
    createdAt: "2024-01-14T08:15:00Z",
    updatedAt: "2024-01-23T15:20:00Z",
  },
  {
    id: "18",
    name: "Professional Makeup Brush Set",
    description: "Complete 12-piece makeup brush set with premium bristles",
    price: 89,
    originalPrice: 129,
    images: [
      "/makeup-brush-set.png",
      "/brushes-individual.png",
      "/brush-case.png",
    ],
    category: "Health & Beauty",
    subcategory: "Makeup",
    brand: "BeautyPro",
    stock: 45,
    rating: 4.7,
    reviewCount: 167,
    featured: true,
    tags: ["makeup", "brushes", "professional", "beauty"],
    specifications: {
      "Brush Count": "12 pieces",
      Bristles: "Synthetic",
      Handle: "Wooden",
      Case: "Included",
    },
    variations: [
      {
        id: "18-12brushes",
        name: "12 Brushes",
        price: 89,
        stock: 45,
        sku: "MAKEUPBRUSHSET-12",
      },
      {
        id: "18-24brushes",
        name: "24 Brushes",
        price: 129,
        stock: 40,
        sku: "MAKEUPBRUSHSET-24",
      },
    ],
    mainFeatures: [
      "Complete 12-piece makeup brush set",
      "Premium synthetic bristles for smooth application",
      "Wooden handle for durability and comfort",
      "Included case for easy storage",
      "Available in multiple sizes",
    ],
    keyFeatures: [
      "Ideal for professional makeup artists",
      "Versatile brushes for various makeup techniques",
      "Easy to clean and maintain",
      "Available in various colors",
      "Stylish and elegant design",
      "Built-in storage case for organization",
    ],
    whatsInTheBox: [
      "Professional Makeup Brush Set",
      "Cleaning Cloth",
      "User Manual",
    ],
    createdAt: "2024-01-03T10:30:00Z",
    updatedAt: "2024-01-13T12:45:00Z",
  },
  {
    id: "19",
    name: "Adjustable Dumbbells Set",
    description: "Space-saving adjustable dumbbells for home workouts",
    price: 299,
    originalPrice: 399,
    images: [
      "/adjustable-dumbbells.png",
      "/dumbbells-weights.png",
      "/dumbbells-rack.png",
    ],
    category: "Sports & Outdoors",
    subcategory: "Fitness Equipment",
    brand: "FitHome",
    stock: 16,
    rating: 4.8,
    reviewCount: 234,
    featured: true,
    tags: ["dumbbells", "adjustable", "fitness", "home-gym"],
    specifications: {
      "Weight Range": "5-50 lbs per dumbbell",
      Material: "Cast Iron with Rubber Coating",
      "Space Required": "Minimal",
      Warranty: "2 Years",
    },
    variations: [
      {
        id: "19-5lbs",
        name: "5 lbs",
        price: 299,
        stock: 16,
        sku: "ADUMBBELLS-5",
      },
      {
        id: "19-10lbs",
        name: "10 lbs",
        price: 349,
        stock: 14,
        sku: "ADUMBBELLS-10",
      },
    ],
    mainFeatures: [
      "Adjustable weight range for versatile workouts",
      "Cast Iron construction for durability",
      "Rubber coating for comfortable grip",
      "Minimal space required for easy storage",
      "Available in multiple weights",
    ],
    keyFeatures: [
      "Ideal for home gym setups",
      "Compact design for space-saving",
      "Easy to adjust weights",
      "Available in various colors",
      "Built-in rack for convenient storage",
      "2-year warranty for peace of mind",
    ],
    whatsInTheBox: [
      "Adjustable Dumbbells Set",
      "Adjustment Tools",
      "User Manual",
    ],
    createdAt: "2024-01-02T09:15:00Z",
    updatedAt: "2024-01-12T11:30:00Z",
  },
  {
    id: "20",
    name: "Camping Tent 4-Person",
    description: "Waterproof family camping tent with easy setup",
    price: 149,
    originalPrice: 199,
    images: [
      "/camping-tent-4-person.png",
      "/tent-interior.png",
      "/tent-setup.png",
    ],
    category: "Sports & Outdoors",
    subcategory: "Outdoor Gear",
    brand: "OutdoorLife",
    stock: 27,
    rating: 4.5,
    reviewCount: 156,
    featured: false,
    tags: ["tent", "camping", "waterproof", "family"],
    specifications: {
      Capacity: "4 Person",
      "Floor Area": "64 sq ft",
      "Peak Height": "6 ft",
      "Setup Time": "10 minutes",
    },
    variations: [
      {
        id: "20-4person",
        name: "4 Person",
        price: 149,
        stock: 27,
        sku: "CAMPINGTENT-4P",
      },
      {
        id: "20-6person",
        name: "6 Person",
        price: 199,
        stock: 22,
        sku: "CAMPINGTENT-6P",
      },
    ],
    mainFeatures: [
      "Waterproof design for reliable protection",
      "4-person capacity for family use",
      "64 sq ft floor area for ample space",
      "Easy setup with minimal tools",
      "Available in multiple sizes",
    ],
    keyFeatures: [
      "Ideal for family camping trips",
      "Compact design for easy transportation",
      "Built-in storage pockets for essentials",
      "Available in various colors",
      "Sturdy construction for durability",
      "Easy to clean and maintain",
    ],
    whatsInTheBox: [
      "Camping Tent",
      "Tent Poles",
      "Carabiners",
      "Stakes",
      "Quick Start Guide",
    ],
    createdAt: "2024-01-01T15:45:00Z",
    updatedAt: "2024-01-11T17:20:00Z",
  },
  {
    id: "21",
    name: "Baby Stroller Travel System",
    description: "Complete travel system with car seat and base",
    price: 399,
    originalPrice: 499,
    images: [
      "/baby-stroller-system.png",
      "/stroller-car-seat.png",
      "/stroller-folded.png",
    ],
    category: "Baby Products",
    subcategory: "Baby Gear",
    brand: "SafeRide",
    stock: 19,
    rating: 4.9,
    reviewCount: 278,
    featured: true,
    tags: ["stroller", "car-seat", "travel-system", "safety"],
    specifications: {
      "Age Range": "Birth to 4 years",
      "Weight Limit": "50 lbs",
      "Car Seat": "Included",
      "Safety Rating": "5-Star",
    },
    variations: [
      {
        id: "21-standard",
        name: "Standard",
        price: 399,
        stock: 19,
        sku: "BABYSTROLLER-STD",
      },
      {
        id: "21-pro",
        name: "Pro",
        price: 499,
        stock: 15,
        sku: "BABYSTROLLER-PRO",
      },
    ],
    mainFeatures: [
      "Complete travel system with car seat and base",
      "Suitable for babies from birth to 4 years",
      "50 lbs weight limit for safety",
      "Included car seat for added convenience",
      "Available in multiple sizes",
    ],
    keyFeatures: [
      "Ideal for family travel",
      "Compact design for easy transportation",
      "Built-in storage pockets for essentials",
      "Available in various colors",
      "Sturdy construction for durability",
      "Easy to clean and maintain",
    ],
    whatsInTheBox: [
      "Baby Stroller Travel System",
      "Car Seat",
      "Base",
      "Adjustment Tools",
      "User Manual",
    ],
    createdAt: "2023-12-30T14:20:00Z",
    updatedAt: "2024-01-10T16:35:00Z",
  },
  {
    id: "22",
    name: "Educational Building Blocks",
    description: "Colorful building blocks for developing motor skills",
    price: 39,
    originalPrice: 49,
    images: ["/building-blocks.png", "/blocks-colors.png", "/blocks-play.png"],
    category: "Baby Products",
    subcategory: "Toys",
    brand: "LearnPlay",
    stock: 78,
    rating: 4.6,
    reviewCount: 189,
    featured: false,
    tags: ["toys", "educational", "building", "motor-skills"],
    specifications: {
      "Age Range": "12 months+",
      "Piece Count": "50 blocks",
      Material: "BPA-Free Plastic",
      "Safety Certified": "Yes",
    },
    variations: [
      {
        id: "22-50blocks",
        name: "50 Blocks",
        price: 39,
        stock: 78,
        sku: "BUILDINGBLOCKS-50",
      },
      {
        id: "22-100blocks",
        name: "100 Blocks",
        price: 49,
        stock: 70,
        sku: "BUILDINGBLOCKS-100",
      },
    ],
    mainFeatures: [
      "Colorful building blocks for engaging play",
      "50-piece set for developing motor skills",
      "BPA-Free plastic for safety",
      "Safety certified for peace of mind",
      "Available in multiple sizes",
    ],
    keyFeatures: [
      "Ideal for early childhood development",
      "Encourages creativity and problem-solving",
      "Compact design for easy storage",
      "Available in various colors",
      "Sturdy construction for durability",
      "Easy to clean and maintain",
    ],
    whatsInTheBox: [
      "Educational Building Blocks",
      "Storage Container",
      "User Manual",
    ],
    createdAt: "2023-12-29T12:10:00Z",
    updatedAt: "2024-01-09T14:25:00Z",
  },
];

export const banners: Banner[] = [
  {
    id: "1",
    title: "New Year Sale",
    subtitle: "Up to 50% off on selected items",
    image: "/new-year-sale-banner.jpg",
    link: "/promotions/new-year-sale",
    buttonText: "Shop Now",
    active: true,
    order: 1,
  },
  {
    id: "2",
    title: "Latest Electronics",
    subtitle: "Discover cutting-edge technology",
    image: "/electronics-banner.png",
    link: "/categories/electronics",
    buttonText: "Explore",
    active: true,
    order: 2,
  },
  {
    id: "3",
    title: "Fashion Forward",
    subtitle: "Trending styles for every season",
    image: "/fashion-banner.png",
    link: "/categories/fashion",
    buttonText: "Shop Fashion",
    active: true,
    order: 3,
  },
];

export const promotions: Promotion[] = [
  {
    id: "1",
    title: "New Year Mega Sale",
    description: "Get up to 50% off on electronics and fashion items",
    discountType: "percentage",
    discountValue: 50,
    code: "NEWYEAR50",
    startDate: "2024-01-01T00:00:00Z",
    endDate: "2024-01-31T23:59:59Z",
    active: true,
    applicableCategories: ["Phones and Tablets", "Computers", "Fashion"],
  },
  {
    id: "2",
    title: "Free Shipping Weekend",
    description: "Free shipping on all orders above Ugx 20,000",
    discountType: "fixed",
    discountValue: 0,
    startDate: "2024-01-26T00:00:00Z",
    endDate: "2024-01-28T23:59:59Z",
    active: true,
  },
];

export const reviews: Review[] = [
  {
    id: "1",
    productId: "1",
    customerName: "John Smith",
    customerEmail: "john@example.com",
    rating: 5,
    title: "Amazing phone!",
    comment:
      "The iPhone 15 Pro Max exceeded my expectations. The camera quality is incredible and the battery life is outstanding.",
    verified: true,
    helpful: 12,
    createdAt: "2024-01-20T14:30:00Z",
  },
  {
    id: "2",
    productId: "2",
    customerName: "Sarah Johnson",
    customerEmail: "sarah@example.com",
    rating: 5,
    title: "Perfect for work",
    comment:
      "This MacBook Pro handles all my design work effortlessly. The display is stunning and performance is top-notch.",
    verified: true,
    helpful: 8,
    createdAt: "2024-01-18T16:45:00Z",
  },
  {
    id: "3",
    productId: "3",
    customerName: "Mike Davis",
    customerEmail: "mike@example.com",
    rating: 4,
    title: "Great noise cancellation",
    comment:
      "These headphones are fantastic for travel. The noise cancellation works really well on flights.",
    verified: true,
    helpful: 15,
    createdAt: "2024-01-22T13:15:00Z",
  },
];

export const testimonials: Testimonial[] = [
  {
    id: "1",
    customerName: "Emily Chen",
    customerImage: "/customer-profile-woman.jpg",
    rating: 5,
    comment:
      "Excellent service and fast delivery. The products are exactly as described and the quality is outstanding.",
    location: "New York, NY",
    verified: true,
    featured: true,
    createdAt: "2024-01-15T10:00:00Z",
  },
  {
    id: "2",
    customerName: "David Wilson",
    customerImage: "/customer-profile-man.jpg",
    rating: 5,
    comment:
      "I've been shopping here for months and never had a bad experience. Great customer support and competitive prices.",
    location: "Los Angeles, CA",
    verified: true,
    featured: true,
    createdAt: "2024-01-12T11:30:00Z",
  },
  {
    id: "3",
    customerName: "Lisa Rodriguez",
    customerImage: "/customer-profile-woman-hispanic.jpg",
    rating: 5,
    comment:
      "The website is easy to navigate and the checkout process is smooth. Highly recommend this store!",
    location: "Miami, FL",
    verified: true,
    featured: true,
    createdAt: "2024-01-10T09:00:00Z",
  },
];
