import type {
  Product,
  Category,
  Banner,
  Promotion,
  Review,
  Testimonial,
} from "./types";

export const categories: Category[] = [
  {
    id: "1",
    name: "Phones and Tablets",
    slug: "phones-tablets",
    description: "Latest smartphones and tablets",
    image: "/phones-tablets-category.png",
    icon: "📱",
    productCount: 85,
    subcategories: [
      {
        id: "1-1",
        name: "Smartphones",
        slug: "smartphones",
        description: "Latest smartphones",
        image: "/modern-smartphones.png",
      },
      {
        id: "1-2",
        name: "Tablets",
        slug: "tablets",
        description: "High-performance tablets",
        image: "/various-tablets.png",
      },
      {
        id: "1-3",
        name: "Accessories",
        slug: "phone-accessories",
        description: "Phone and tablet accessories",
        image: "/phone-accessories.png",
      },
    ],
  },
  {
    id: "2",
    name: "Computing",
    slug: "computing",
    description: "Laptops, desktops and computer accessories",
    image: "/computers-category.png",
    icon: "💻",
    productCount: 67,
    subcategories: [
      {
        id: "2-1",
        name: "Laptops",
        slug: "laptops",
        description: "High-performance laptops",
        image: "/various-laptops.png",
      },
      {
        id: "2-2",
        name: "Desktops",
        slug: "desktops",
        description: "Desktop computers",
        image: "/desktop-computers.png",
      },
      {
        id: "2-3",
        name: "Computer Accessories",
        slug: "computer-accessories",
        description: "Keyboards, mice, monitors",
        image: "/computer-accessories.png",
      },
    ],
  },
  {
    id: "3",
    name: "Electronics",
    slug: "electronics",
    description: "Audio, gaming and electronic devices",
    image: "/electronics-category.png",
    icon: "🎧",
    productCount: 92,
    subcategories: [
      {
        id: "3-1",
        name: "Headphones",
        slug: "headphones",
        description: "Premium audio devices",
        image: "/diverse-people-listening-headphones.png",
      },
      {
        id: "3-2",
        name: "Gaming",
        slug: "gaming",
        description: "Gaming consoles and accessories",
        image: "/gaming-devices.png",
      },
      {
        id: "3-3",
        name: "Smart Home",
        slug: "smart-home",
        description: "Smart home devices",
        image: "/smart-home-devices.png",
      },
    ],
  },
  {
    id: "4",
    name: "Fashion",
    slug: "fashion",
    description: "Trendy clothing and accessories",
    image: "/fashion-category.png",
    icon: "👗",
    productCount: 234,
    subcategories: [
      {
        id: "4-1",
        name: "Men's Clothing",
        slug: "mens-clothing",
        description: "Stylish men's wear",
        image: "/mens-clothing-display.png",
      },
      {
        id: "4-2",
        name: "Women's Clothing",
        slug: "womens-clothing",
        description: "Trendy women's fashion",
        image: "/womens-clothing.png",
      },
      {
        id: "4-3",
        name: "Accessories",
        slug: "accessories",
        description: "Fashion accessories",
        image: "/fashion-accessories-collection.png",
      },
    ],
  },
  {
    id: "5",
    name: "Home & Office",
    slug: "home-office",
    description: "Furniture and office supplies",
    image: "/home-office-category.jpg",
    icon: "🏠",
    productCount: 189,
    subcategories: [
      {
        id: "5-1",
        name: "Furniture",
        slug: "furniture",
        description: "Quality furniture pieces",
        image: "/assorted-living-room-furniture.png",
      },
      {
        id: "5-2",
        name: "Office Supplies",
        slug: "office-supplies",
        description: "Essential office items",
        image: "/assorted-office-supplies.png",
      },
      {
        id: "5-3",
        name: "Home Decor",
        slug: "home-decor",
        description: "Beautiful home decorations",
        image: "/cozy-living-room.png",
      },
    ],
  },
  {
    id: "6",
    name: "Health & Beauty",
    slug: "health-beauty",
    description: "Personal care and wellness products",
    image: "/health-beauty-category.jpg",
    icon: "💄",
    productCount: 145,
    subcategories: [
      {
        id: "6-1",
        name: "Skincare",
        slug: "skincare",
        description: "Premium skincare products",
        image: "/skincare-products-display.png",
      },
      {
        id: "6-2",
        name: "Makeup",
        slug: "makeup",
        description: "Quality makeup products",
        image: "/makeup-products-flatlay.png",
      },
      {
        id: "6-3",
        name: "Wellness",
        slug: "wellness",
        description: "Health and wellness items",
        image: "/wellness-products-still-life.png",
      },
    ],
  },
  {
    id: "7",
    name: "Sports & Outdoors",
    slug: "sports-outdoors",
    description: "Sports equipment and outdoor gear",
    image: "/sports-outdoors-category.jpg",
    icon: "⚽",
    productCount: 167,
    subcategories: [
      {
        id: "7-1",
        name: "Fitness Equipment",
        slug: "fitness-equipment",
        description: "Home fitness gear",
        image: "/diverse-fitness-equipment.png",
      },
      {
        id: "7-2",
        name: "Outdoor Gear",
        slug: "outdoor-gear",
        description: "Camping and hiking gear",
        image: "/assorted-outdoor-gear.png",
      },
      {
        id: "7-3",
        name: "Sports Apparel",
        slug: "sports-apparel",
        description: "Athletic clothing",
        image: "/diverse-sports-apparel.png",
      },
    ],
  },
  {
    id: "8",
    name: "Baby Products",
    slug: "baby-products",
    description: "Everything for your little ones",
    image: "/baby-products-category.jpg",
    icon: "👶",
    productCount: 98,
    subcategories: [
      {
        id: "8-1",
        name: "Baby Clothing",
        slug: "baby-clothing",
        description: "Comfortable baby clothes",
        image: "/baby-clothing.jpg",
      },
      {
        id: "8-2",
        name: "Baby Gear",
        slug: "baby-gear",
        description: "Essential baby equipment",
        image: "/baby-gear.jpg",
      },
      {
        id: "8-3",
        name: "Toys",
        slug: "toys",
        description: "Educational and fun toys",
        image: "/colorful-baby-toys.png",
      },
    ],
  },
];

export const products: Product[] = [
  {
    id: "1",
    name: "Samsung Galaxy Z Fold 6 Case With S Pen Holder & Stylus, Hard PC Shockproof Protective Cover For Galaxy Z Fold6 5G",
    description:
      "This case is only suitable for Samsung Galaxy Z Fold 6 and is not compatible with other models.",
    price: 550000,
    originalPrice: 850000,
    images: [
      "/phones_and_tablets/galaxyfold.jpg",
      "/phones_and_tablets/galaxyfold2.jpg",
      "/phones_and_tablets/galaxyfold3.jpg",
    ],
    category: "Phones and Tablets",
    subcategory: "Smartphones",
    brand: "Samsung",
    stock: 6,
    rating: 4.8,
    reviewCount: 342,
    featured: true,
    tags: ["smartphone", "samsung", "premium", "latest"],
    specifications: {
      SKU: "SA948EA3ICKJ1NAFAMZ",
      Weight: "0.03kg",
      Color: "Black",
      Main_Material: "Leather",
    },
    variations: [
      {
        id: "1-128",
        name: "Fold 5",
        price: 480000,
        originalPrice: 850000,
        stock: 5,
      },
      {
        id: "1-256",
        name: "Fold 6",
        price: 550000,
        originalPrice: 850000,
        stock: 2,
      },
    ],
    mainFeatures: [
      "100% fashionable and durable. Offering a sophisticated look and great feel.",
      ".Corner bumpers protection for drops. Soft materials offer maximum protection from bumps and hard-hits for the back and sides of your phone.",
      "All buttons and corners are elevated, and raised edges lift the screen and camera lens off the surface.",
      "Keep your phone in like-new condition well and preserves its looks and features, to protect your phone hurt from scratches and gives you mobile phone a special look.",
    ],
    keyFeatures: [
      "This case is only suitable for Samsung Galaxy Z Fold 6 and is not compatible with other models.",
      "Precise Cutouts: Wide cutouts and responsive press keys, as well as easy access to all ports, buttons, cameras, speakers, and mics.",
      "Stable & Durable – Raised beveled edge keeps your touchscreen safe, dust protection, scratch protection and drop protection.",
      "A comprehensive new upgraded anti-fall protective cover with novel and fashionable appearance.",
      "Keeps your device thin and form fitting to fit right in your pocket and bag. This fantastic cases gives your phone a fresh look, and it could be a perfect gift.",
    ],
    whatsInTheBox: ["Cover", "Pen"],
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-20T14:30:00Z",
  },
  {
    id: "2",
    name: "Samsung Tab A9 Folio Slim Lightweight Tablet Case",
    description: "Premium Android smartphone with S Pen and AI features",
    price: 145000,
    originalPrice: 250000,
    images: [
      "/phones_and_tablets/galaxycase.jpg",
      "/phones_and_tablets/galaxycase2.jpg",
      "/phones_and_tablets/galaxycase3.jpg",
    ],
    category: "Phones and Tablets",
    subcategory: "Accessories",
    brand: "Samsung",
    stock: 5,
    rating: 4.7,
    reviewCount: 289,
    featured: true,
    tags: ["smartphone", "samsung", "android", "phonecase"],
    specifications: {
      SKU: "SA948EA3P8WFQNAFAMZ",
      Weight: "0.05kg",
      Color: "Black",
    },
    variations: [
      {
        id: "7-256",
        name: "A7 Lite",
        price: 95000,
        originalPrice: 250000,
        stock: 10,
      },
      {
        id: "7-512",
        name: "A9",
        price: 145000,
        originalPrice: 250000,
        stock: 18,
      },
      {
        id: "7-1tb",
        name: "A9 Plus",
        price: 155000,
        originalPrice: 250000,
        stock: 2,
      },
    ],
    mainFeatures: [
      "Built-in smart cover auto on/auto sleep function.",
      "Compact, elegant, stylish, easy to install and remove.",
      "Convenient position for watching movies or writing.",
      "100% high quality, customized and fits your tablet perfectly.",
      "Against unwanted bumps, accidental drops, scratches, bruises or stains.",
      "Package includes one (1) protective case.",
    ],
    keyFeatures: ["Protective.", "Black.", "Flip.", "Both sides covered."],
    whatsInTheBox: ["Phone Case"],
    createdAt: "2024-01-12T09:30:00Z",
    updatedAt: "2024-01-22T11:15:00Z",
  },
  {
    id: "3",
    name: "Samsung Galaxy Z Fold 6 Case With Screen Guard",
    description:
      "Samsung Galaxy Z Fold 6 Case with S Pen Holder & Stylus, Hard PC Shockproof Protective Cover for Galaxy Z Fold6 5GCompatibility",
    price: 250000,
    originalPrice: 650000,
    images: ["/phones_and_tablets/galaxyfoldcase.jpg"],
    category: "Phones and Tablets",
    subcategory: "Accessories",
    brand: "Samsung",
    stock: 4,
    rating: 4.9,
    reviewCount: 156,
    featured: true,
    tags: ["case", "samsung", "professional"],
    specifications: {
      SKU: "SA948EA3ZJZWTNAFAMZ",
      Weight: "0.05kg",
      Certifications: "Eco Friendly",
      Camera: "Black",
      From_the_Manufacturer: "Durable and Protective",
      Warranty_Address: "Zebra Plaza",
    },
    variations: [
      {
        id: "8-128",
        name: "Fold 6",
        price: 250000,
        originalPrice: 650000,
        stock: 3,
      },
    ],
    mainFeatures: [
      "This case is only suitable for Samsung Galaxy Z Fold 6 and is not compatible with other models.",
      "Please Note: Please confirm your phone model before buying.",
      "Fashionabl and durable. Offering a sophisticated look and great feel.",
      "Keep your phone in like-new condition well and preserves its looks and features, to protect your phone hurt from scratches and gives you mobile phone a special look.",
    ],
    keyFeatures: [
      "This case is only suitable for Samsung Galaxy Z Fold 6 and is not compatible with other models.",
      "Precise Cutouts: Wide cutouts and responsive press keys, as well as easy access to all ports, buttons, cameras, speakers, and mics.",
      "Stable & Durable – Raised beveled edge keeps your touchscreen safe, dust protection, scratch protection and drop protection.",
      "A comprehensive new upgraded anti-fall protective cover with novel and fashionable appearance.",
      "Keeps your device thin and form fitting to fit right in your pocket and bag. This fantastic cases gives your phone a fresh look, and it could be a perfect gift.",
    ],
    whatsInTheBox: ["Cover", "Screen Guard"],
    createdAt: "2024-01-10T14:20:00Z",
    updatedAt: "2024-01-25T16:45:00Z",
  },
  {
    id: "4",
    name: "Defender Shock Proof for Galaxy Tab A9",
    description: "Defender Shock Proof for Galaxy Tab A9 / A9 Plus BLACK",
    price: 250000,
    originalPrice: 650000,
    images: [
      "/phones_and_tablets/galaxyshockproof.jpg",
      "/phones_and_tablets/galaxyshockproof2.jpg",
      "/phones_and_tablets/galaxyshockproof3.jpg",
    ],
    category: "Phones and Tablets",
    subcategory: "Accessories",
    brand: "Samsung",
    stock: 4,
    rating: 4.5,
    reviewCount: 78,
    featured: false,
    tags: ["case", "samsung", "protection"],
    specifications: {
      SKU: "GE779EA48AN87NAFAMZ",
      Weight: "350g",
      Color: "Black",
    },
    variations: [
      {
        id: "9-galaxyA9",
        name: "A9",
        price: 250000,
        originalPrice: 650000,
        stock: 3,
      },
      {
        id: "9-galaxyA9Plus",
        name: "A9 Plus",
        price: 350000,
        originalPrice: 650000,
        stock: 4,
      },
    ],
    mainFeatures: [
      "Defender provides protection for all Samsung tablets for more protection and 360 rotating angles.",
    ],
    keyFeatures: [
      "Shell Type: Hard",
      "Brand: Seymac",
      "Target Gender: Unisex",
      "Color: Black / Black",
      "Theme: Tablet Case",
      "Model Number: For Samsung Galaxy Tab A9+, A9",
    ],
    whatsInTheBox: ["Cover"],
    createdAt: "2024-01-08T11:00:00Z",
    updatedAt: "2024-01-20T13:30:00Z",
  },
  {
    id: "5",
    name: 'Samsung Galaxy A16 4G 6.7" 8GB RAM 256GB ROM 50MP 5000mAh - Black"',
    description: "Powerful laptop with M3 Pro chip for professional workflows",
    price: 950000,
    images: ["/phones_and_tablets/galaxya16.jpg"],
    category: "Phones and Tablets",
    subcategory: "Smartphones",
    brand: "Samsung",
    stock: 3,
    rating: 4.9,
    reviewCount: 128,
    featured: true,
    tags: ["galaxy", "samsung"],
    specifications: {
      SKU: "SA948MP3LS5BFNAFAMZ",
      Weight: "0.19kg",
      Color: "Black",
    },
    variations: [
      {
        id: "2-m3pro",
        name: "A15 256",
        price: 950000,
        stock: 3,
      },
    ],
    mainFeatures: [
      "Dive into your favourite content with the stunning clarity and vibrant colours of Galaxy A16 4G's FHD+ Super AMOLED display. The expansive 6.7-inch screen with minimised bezels brings every moment to life.",
      "Slimmed down to just 7.9mm in thickness, Galaxy A16 4G slips right into your hand, pocket and daily life. Available in Blue Black, Light Grey and Light Green, it combines elegant design with enhanced portability.",
      "Take high-quality shots of your everyday life with advanced camera features. Capture memories vividly with a 50MP Main Camera, take clear selfies with a 13MP Front Camera to make each moment shine.",
      "With the upgraded 2.4GHz CPU, you can power through your foes fast and stream your favorite show without missing a beat.",
      "Enjoy what you love without worrying about battery life—the 5,000mAh battery keeps Galaxy A16 4G running strong on a single charge. Plus with Super Fast Charging, it's back in action quickly.",
    ],
    keyFeatures: [
      "Network Technology: GSM / HSPA / LTE",
      "SIM: Hybrid Dual SIM (Nano-SIM, dual stand-by)",
      "Size: 6.7 inches, 110.2 cm2 (~86.0% screen-to-body ratio)",
      "Platform: OS Android 14, up to 6 major Android upgrades, One UI 6.1",
      "Internal: 256GB 8GB RAM",
      "Main Camera: Triple 50 MP",
      "Comms: WLAN Wi-Fi 802.11 a/b/g/n/ac, dual-band, Wi-Fi Direct",
      "Bluetooth: 5.3, A2DP, LE",
      "USB: USB Type-C 2.0",
      "Battery Type: 5000 mAh, non-removable",
    ],
    whatsInTheBox: ["Samsung Galaxy A16"],
    createdAt: "2024-01-10T09:00:00Z",
    updatedAt: "2024-01-18T16:45:00Z",
  },
  {
    id: "6",
    name: "Silicone Case For Samsung Galaxy S8 S9 S10 Plus",
    description:
      "Silicone Case For Samsung Galaxy S8 S9 S10 Plus S6 S7 Edge S4 S5 Neo Note 8 9 3 4 5 A3 A5 A7 2015 2016 2017 Luxury Phone Cover(Purple)",
    price: 45000,
    originalPrice: 87000,
    images: ["/phones_and_tablets/siliconecase.jpg"],
    category: "Phones and Tablets",
    subcategory: "Accessories",
    brand: "",
    stock: 22,
    rating: 4.6,
    reviewCount: 94,
    featured: false,
    tags: ["samsung", "silicon", "case"],
    specifications: {
      SKU: "GE779EA46SQYZNAFAMZ",
      Size: "10cm x 5cm x 1cm",
      Weight: "0.03kg",
    },
    variations: [
      {
        id: "10-i5",
        name: "Note 8",
        price: 87000,
        originalPrice: 87000,
        stock: 4,
      },
      {
        id: "10-i7",
        name: "Note 9",
        price: 87000,
        originalPrice: 87000,
        stock: 3,
      },
      {
        id: "10-s8-1tb",
        name: "S8 Plus",
        price: 87000,
        originalPrice: 87000,
        stock: 3,
      },
      {
        id: "10-i7-plus",
        name: "S9 Plus",
        price: 48000,
        originalPrice: 87000,
        stock: 3,
      },
      {
        id: "10-s10-1tb",
        name: "S10",
        price: 87000,
        originalPrice: 87000,
        stock: 3,
      },
      {
        id: "10-s10pl-1tb",
        name: "S10 Plus",
        price: 45000,
        originalPrice: 87000,
        stock: 3,
      },
    ],
    mainFeatures: [
      "Customer satisfaction is very important for us. If you are satisfied with the items you ordered, please leave 9833 stars feedback. If you are not satisfied with our products or service, please let us know and give us the opportunity to make things right. thank you.",
    ],
    keyFeatures: [
      "Retail Package:Yes",
      "Type:Fitted Case",
      "Function:Dirt-resistant, Anti-knock, Heavy Duty Protection",
      "Compatible Brand:Samsung",
      "Compatible Samsung Model:Galaxy Note4, I9500 GALAXY S IV, Galaxy S5, Galaxy S6, Galaxy S6 edge, GALAXY S6 EDGE PLUS, Note 5, Galaxy Note III, Galaxy S8, Galaxy S8 Plus, Galaxy S7, Galaxy S7 Edge, Galaxy Note 8, Galaxy S9, Galaxy Note 9",
      "Design:Sports, Business, Matte, Cute, Plain",
      "Size:S 6 7 S6edge S7edge S8Plus S9Plus Note8 Pink Black Purple blue Girl design",
      "Features:Origin Mobile accessory Housing Casing Coque Woman",
      "Material:Soft Silicone",
      "Quality:100% New Brand High Quality Durable Flexible Touch Bag shell funda",
      "Model 1:Fundas For Samsung galaxy G900 G920 G925 G930 G935 G950 G955",
      "Model 2:capa For Samsung galaxy G900f G920f G925f G930f G935f G950f G955f",
      "Model 3:cases For Samsung S 5 6 7 8 S5neo S6edge S7edge S8Plus",
      "Features:Fashion Magnetic holder Pretty High Quality bags fundas capa shells",
      "Colors:Red , Pink , Yellow , Purple , Black , Blue , Green , white",
    ],
    whatsInTheBox: [],
    createdAt: "2024-01-14T10:30:00Z",
    updatedAt: "2024-01-24T14:20:00Z",
  },
  {
    id: "7",
    name: "Samsung Wireless Super Fast Charging Powerbank",
    description: "Samsung Wireless Super Fast Charging Powerbank",
    price: 285000,
    originalPrice: 350000,
    images: [
      "/phones_and_tablets/samsungpowerbank.jpg",
      "/phones_and_tablets/samsungpowerbank2.jpg",
      "/phones_and_tablets/samsungpowerbank3.jpg",
      "/phones_and_tablets/samsungpowerbank4.jpg",
      "/phones_and_tablets/samsungpowerbank5.jpg",
    ],
    category: "Phones and Tablets",
    subcategory: "Accessories",
    brand: "Samsung",
    stock: 8,
    rating: 4.8,
    reviewCount: 67,
    featured: true,
    tags: ["powerbank", "samsung", "fastcharger"],
    specifications: {
      SKU: "SA948EA4RMX57NAFAMZ",
      Weight: "0.05kg",
      Color: "May Vary",
      Main_Material: "PvC",
      From_the_Manufacturer: "Keep away from heat or fire",
    },
    variations: [
      {
        id: "11-rtx4070",
        name: "3rtt",
        price: 285000,
        stock: 8,
      },
    ],
    mainFeatures: [
      "Samsung Wireless Portable Power Bank best price in Kenya. Recharge both wired and wireless devices with this 25W USB Type-C Wireless Portable Power Bank from Samsung. The power bank features two USB Type-C ports and a built-in Qi-compatible wireless charging pad. This gives you the ability to recharge up to three devices simultaneously, spanning a wide array of categories, such as wireless headphones, smartwatches, and smartphones.",
      "The battery can fast charge up to two wired devices at up to 25W, while the wireless pad provides up to 7.5W of power to Qi-compatible products. Four built-in LED status lights conveniently let you know how much power is left in the power bank. When it’s time to recharge the battery, it too can take advantage of up to 25W of fast charging.",
      "Take the convenience of wireless charging on the road. The new Wireless Battery Pack allows you to wirelessly charge your Galaxy S10e, S10, S10+ or Galaxy Watch Active, so you don’t have to worry even when there’s no outlet in sight.",
    ],
    keyFeatures: [
      "Brand: Samsung",
      "Capacity: 10,000000Amh",
      "Wireless Charging",
      "Usb cable",
      "Fast Charging",
    ],
    whatsInTheBox: ["Samsung wireless powerbank", "Cable"],
    createdAt: "2024-01-16T12:00:00Z",
    updatedAt: "2024-01-26T15:30:00Z",
  },
  {
    id: "8",
    name: "Tecno High Speed Portable 4G MIFI open to all All Networks",
    description:
      "Tecno MiFi 8 Users 150Mbps 4G Portable High Speed Wi-Fi Hotspot",
    price: 200000,
    originalPrice: 350000,
    images: [
      "/computing/mifi.jpg",
      "/computing/mifi2.jpg",
      "/computing/mifi3.jpg",
      "/computing/mifi4.jpg",
    ],
    category: "Computing",
    subcategory: "Computer Accessories",
    brand: "Tecno",
    stock: 9,
    rating: 4.7,
    reviewCount: 234,
    featured: true,
    tags: ["mifi", "4g", "wireless"],
    specifications: {
      SKU: "TE339EA45QM33NAFAMZ",
      Weight: "0.03kg",
      Color: "White, Black",
      Main_Material: "Plastic",
      Certifications: "Eco Friendly",
    },
    variations: [
      {
        id: "mifi-4g",
        name: "MiFi",
        price: 200000,
        stock: 9,
      },
    ],
    mainFeatures: [
      "The Tecno MiFi TR109C 4G LTE Portable Device provides a compact and high-speed solution. For wireless internet connectivity. Designed for portability and efficiency, this device delivers robust performance with support for 4G LTE networks. Wi-Fi speeds up to 150 Mbps, making it ideal for both personal and professional use.",
      "Key Features Tecno TR109C MiFi 8 Users 150Mbps 4G.",
      "4G LTE Connectivity: The TR109C supports 4G LTE networks, offering fast and reliable internet speeds. With its capability to reach speeds of up to 150 Mbps, the device ensures smooth browsing, streaming, and downloading. Up to 8 WiFi devices simultaneously including laptops, smartphones, tablets and smart TVs.",
      "Portable Design: Compact and lightweight, the TR109C is easy to carry, fitting conveniently in a pocket or bag.",
      "Single Band WiFi: The MiFi device operates on a single band (typically 2.4 GHz), providing stable and reliable WiFi connectivity for multiple devices. This setup allows users to share the internet with smartphones, tablets, laptops, and other gadgets.",
      "Multiple Device Connectivity: They can connect several devices simultaneously, allowing users to share their internet connection with family, friends, or colleagues. This feature is particularly useful for group settings or collaborative work environments.",
    ],
    keyFeatures: [
      "Item Height: 16 Millimeters",
      "Item Width: 6.1 Centimeters",
      "Product Dimensions: 9.7 x 6.1 x 1.6 cm; 110 Grams",
      "Batteries: 1 Lithium Polymer batteries required. (included)",
      "Item model number: TR109C",
      "Are Batteries Included: Yes",
      "Number of Lithium Ion Cells: 1",
      "Included Components Mifi: 1User Manual",
      "Item Weight: 110g",
    ],
    whatsInTheBox: [],
    createdAt: "2024-01-11T08:45:00Z",
    updatedAt: "2024-01-21T10:15:00Z",
  },
  {
    id: "9",
    name: "Lenovo Laptop Thinkpad X270 , X250 , X260, T440p, T440s , T450, Charger 20V 3.25A 65W USB Pin",
    description:
      "Lenovo Laptop Charger 20V 3.25A 65WCharge and power your laptop with this Laptop Charger",
    price: 98000,
    originalPrice: 450000,
    images: [
      "/computing/thinkpadcharger.jpg",
      "/computing/thinkpadcharger2.jpg",
      "/computing/thinkpadcharger3.jpg",
    ],
    category: "Computing",
    subcategory: "Computer Accessories",
    brand: "Lenovo",
    stock: 4,
    rating: 4.7,
    reviewCount: 256,
    featured: false,
    tags: ["charger", "thinkpad", "fastcharger"],
    specifications: {
      SKU: "LE842EA3R2FZCNAFAMZ",
      Weight: "0.4kg",
      Color: "Black",
    },
    variations: [
      {
        id: "2-std",
        name: "Type 1",
        price: 98000,
        stock: 2,
      },
      {
        id: "2-pro",
        name: "Type 2",
        price: 285000,
        stock: 2,
      },
    ],
    mainFeatures: [
      "This laptop power supply is engineered with enough power to deliver a strong charge to any compatible laptop. This unit gives you surge protection, over-current protection, voltage protection and over-temperature protection to keep your laptop operating and charging at the correct voltage.",
      "Built to safeguard your laptop against damage, this charger will not let you down. Order for this Laptop charger from Jumia Kenya and have it delivered at your doorstep.",
      "This unit gives you surge protection, over-current protection, voltage protection and over-temperature protection to keep your laptop operating and charging at the correct voltage. Built to safeguard your laptop against damage, this charger will not let you down.",
    ],
    keyFeatures: [
      "Surge protection",
      "Over-current protection",
      "Voltage protection",
      "Over-temperature protection",
    ],
    whatsInTheBox: ["Lenovo  Laptop Charger"],
    createdAt: "2024-01-12T11:30:00Z",
    updatedAt: "2024-01-22T13:15:00Z",
  },
  {
    id: "10",
    name: "Hp Mouse Dual Mode Rechargeable Bluetooth Wireless Silent Click",
    description:
      "Hp Mouse Dual Mode Rechargeable Bluetooth Wireless Silent Click - Black.",
    price: 98000,
    originalPrice: 280000,
    images: ["/computing/mouse.jpg", "/computing/mouse2.jpg"],
    category: "Computing",
    subcategory: "Computer Accessories",
    brand: "Hp",
    stock: 12,
    rating: 4.9,
    reviewCount: 445,
    featured: true,
    tags: ["mouse", "hp", "playstation", "next-gen"],
    specifications: {
      SKU: "HP246EA4WGFPWNAFAMZ",
      "Weight (kg)": "0.02",
      Storage: "825GB SSD",
      Color: "Black",
    },
    variations: [
      {
        id: "13-digital",
        name: "1",
        price: 98000,
        stock: 12,
      },
    ],
    mainFeatures: [
      "Get this amazing HP mouse with long lasting rechargeable mouse. Battery lasts for over 14 days and 30 days standby. Dual mode with bluetooth and wireless can work with macbooks, windows and smart tv including other devices.",
    ],
    keyFeatures: [
      "Dual Mode Mouse",
      "Silent",
      "Long Lasting Battery",
      "Bluetooth and Wireless Dongle",
    ],
    whatsInTheBox: [
      "Hp Rechargeable Mouse",
      "1 Charging Cable",
      "1 Usb Receiver",
    ],
    createdAt: "2024-01-09T16:20:00Z",
    updatedAt: "2024-01-19T18:45:00Z",
  },
  {
    id: "11",
    name: "Hp Envy X360 2-in-1 Laptop, Core 5 120U, 8GB RAM, 512GB SSD",
    description:
      "Hp Envy X360 2-in-1 Laptop, Core 5 120U, 8GB RAM, 512GB SSD, 14 FHD Touchscreen Display, Fingerprint Reader, Natural Silver (1YR WRTY)",
    price: 4850000,
    originalPrice: 8800000,
    images: [
      "/computing/hpenvy.jpg",
      "/computing/hpenvy2.jpg",
      "/computing/hpenvy3.jpg",
      "/computing/hpenvy4.jpg",
      "/computing/hpenvy5.jpg",
    ],
    category: "Computing",
    subcategory: "Laptops",
    brand: "Hp",
    stock: 6,
    rating: 4.4,
    reviewCount: 1234,
    featured: true,
    tags: ["hp", "envy", "laptops"],
    specifications: {
      SKU: "HP246CL3L06T0NAFAMZ",
      "Weight (kg)": "1.51",
      Color: "Silver",
    },
    variations: [
      {
        id: "14-white",
        name: "Envy",
        price: 4850000,
        stock: 6,
      },
    ],
    mainFeatures: [
      "The HP Envy x360 14 2-in-1 Laptop PC levels up your work or downtime in every possible way, with an enhanced responsive touchscreen, amazing audio, and advanced collaboration technology —all backed by a design with recycled materials, serious power, plus all the apps and security features you need for an unstoppable you.",
      "Built for the hustle",
      "With the touchscreen and the latest Intel® Processor, this laptop helps make all you do more powerful",
      "Privacy on lock",
      "This laptop layers built-in security with privacy features, like the manual camera shutter and Fingerprint reader",
      "Next-level screen time",
      "The FHD screen, HP Audio Boost, and 9-hour battery life keep you immersed in your favorite shows",
    ],
    keyFeatures: [
      "Display: 14 diagonal, FHD (1920 x 1080), multitouch-enabled, IPS, edge-to-edge glass, micro-edge, 300 nits, low power, 62.5% sRGB",
      "Processor: Intel® Core™ i5-1235U (up to 5.0 GHz with Intel® Turbo Boost Technology, 12 MB L3 cache, 10 cores, 12 threads)",
      "Memory: 8 GB DDR4-3200 MHz RAM (onboard)",
      "Storage: 512 GB PCIe® Gen4 NVMe™ M.2 SSD",
      "Operating System: Windows® 11 Home",
      "Features: Wi-Fi, Webcam, Bluetooth, Fingerprint Reader",
    ],
    whatsInTheBox: [
      "HP Envy x360 2-in-1 Laptop",
      "User Guide",
      "Charging Adapter",
    ],
    createdAt: "2024-01-13T09:15:00Z",
    updatedAt: "2024-01-23T11:30:00Z",
  },
  {
    id: "12",
    name: "Multimedia 2.0 Speaker",
    description: "Multimedia 2.0 Speaker For All - Black",
    price: 57000,
    originalPrice: 135000,
    images: ["/computing/speaker.jpg"],
    category: "Computing",
    subcategory: "Computer Accessories",
    brand: "",
    stock: 12,
    rating: 4.8,
    reviewCount: 892,
    featured: false,
    tags: ["speaker", "loud", "noise-canceling", "music"],
    specifications: {
      SKU: "GE779EA3I4XWONAFAMZ",
      "Weight (kg)": "0.057",
      Color: "Black",
    },
    variations: [],
    mainFeatures: [
      "Durable Plastic Cabinet:Crafted from sturdy plastic, these speakers withstand daily use and travel",
      "USB Powered Convenience:Effortlessly powered via USB, these speakers offer a hassle-free setup for your devices",
      "3.5mm Audio Interface:Connects seamlessly to a variety of devices with its standard 3.5mm audio port",
      "High Output Power:Delivers a powerful audio experience with its 6W output, enhancing your listening sessions",
      "Best Computer Speakers Budget-Connect Computer Speakers To Tv-Portable Design:Compact and lightweight, these speakers are perfect for on-the-go audio enjoyment",
    ],
    keyFeatures: [
      "Pure and elegant sound high-quality with unsurpassed effect",
      "Incompliance with acoustics and algorithm rationale",
      "Flexible sound with distinct tone levels",
      "Small sized design, easy to take",
    ],
    whatsInTheBox: ["2.0 Multimedia Speaker"],
    createdAt: "2024-01-07T14:45:00Z",
    updatedAt: "2024-01-17T16:20:00Z",
  },
  {
    id: "13",
    name: "Other Portable Gently Insert The Instant Bright Usb Light",
    description:
      "Other Portable Gently Insert The Instant Bright Usb Light - Pink",
    price: 15200,
    originalPrice: 28000,
    images: [
      "/computing/usblight.jpg",
      "/computing/usblight2.jpg",
      "/computing/usblight3.jpg",
    ],
    category: "Computing",
    subcategory: "Computer Accessories",
    brand: "Other",
    stock: 8,
    rating: 4.5,
    reviewCount: 89,
    featured: false,
    tags: ["light", "usb", "pink"],
    specifications: {
      SKU: "OT296EA4UD5ERNAFAMZ",
      "Product Line": "USB Lights for Laptop/Power bank",
      Model: "USB LED",
      "Weight (kg)": "0.01",
      Color: "Pink",
      "Main Material": "LED",
    },
    variations: [],
    mainFeatures: [
      "By using lowest work voltage: 5V safety and reliability and high efficiency",
      "USB Connection to any iBook, PowerBook, Cube, PC, NoteBook, PowerBank, Wall Charger",
      "Ultra bright with low power consumption without frequency change",
      "Plug and Play",
      "Powered by USB port, no external power needed",
      "Definitely essential gear for night work",
    ],
    keyFeatures: [
      "Equiped with 6 pcs LED lamp beads",
      "Light weight",
      "Portable",
      "Energy-efficiency",
      "Soft lighting to avoid eye fatigue",
    ],
    whatsInTheBox: ["1 Led light"],
    createdAt: "2024-01-08T14:20:00Z",
    updatedAt: "2024-01-19T10:30:00Z",
  },
  {
    id: "14",
    name: "Hp Elitebook 840 G3 , Adapter Charger Pin",
    description:
      "Hp Elitebook 840 G3 , Adapter Charger Pin - Complete With Power Cable -Black",
    price: 155000,
    originalPrice: 290000,
    images: ["/computing/adapter.jpg", "/computing/adapter2.jpg"],
    category: "Computing",
    subcategory: "Computer Accessories",
    brand: "Hp",
    stock: 6,
    rating: 4.6,
    reviewCount: 145,
    featured: true,
    tags: ["hp", "adapter", "charger"],
    specifications: {
      SKU: "HP246EA3XM7MWNAFAMZ",
      "Weight (kg)": "0.5",
      Color: "Black",
    },
    variations: [
      {
        id: "16-bigpin",
        name: "Big Pin",
        price: 155000,
        originalPrice: 290000,
        stock: 3,
      },
      {
        id: "16-smallpin",
        name: "Small Pin",
        price: 165000,
        originalPrice: 290000,
        stock: 3,
      },
    ],
    mainFeatures: [
      "HP Laptop Charger 19.5V, 3.33A",
      "Charge and power your laptop with this Laptop Charger. This laptop power supply is engineered with enough power to deliver a strong charge to any compatible laptop. This unit gives you surge protection, over-current protection, voltage protection and over-temperature protection to keep your laptop operating and charging at the correct voltage",
      "Built to safeguard your laptop against damage, this charger will not let you down. Order for this Laptop charger from Jumia Kenya and have it delivered at your doorstep",
      "This unit gives you surge protection, over-current protection, voltage protection and over-temperature protection to keep your laptop operating and charging at the correct voltage. Built to safeguard your laptop against damage, this charger will not let you down",
    ],
    keyFeatures: [
      "Surge protection",
      "Over-current protection",
      "Voltage protection",
      "Over-temperature protection",
    ],
    whatsInTheBox: ["HP charger"],
    createdAt: "2024-01-06T13:30:00Z",
    updatedAt: "2024-01-16T15:45:00Z",
  },
  {
    id: "15",
    name: "Hp Refurbished EliteBook 820 Core I5 8GB RAM 500gb Hdd Slim Laptop",
    description:
      "Hp Refurbished EliteBook 820 Core I5 8GB RAM 500gb Hdd Slim Laptop - Black/sliver",
    price: 950000,
    originalPrice: 1350000,
    images: [
      "/computing/elitebook.jpg",
      "/computing/elitebook2.jpg",
      "/computing/elitebook3.jpg",
    ],
    category: "Computing",
    subcategory: "Laptops",
    brand: "Hp",
    stock: 7,
    rating: 4.6,
    reviewCount: 167,
    featured: true,
    tags: ["laptop", "hpelitebook", "hp", "elitebook"],
    specifications: {
      SKU: "HP246CL41RF0BNAFAMZ",
      "Weight Capacity": "300 lbs",
      Model: "Height, Armrests, Lumbar",
      Warranty: "5 Years",
    },
    variations: [
      {
        id: "5-hp820",
        name: "Hp 820",
        price: 950000,
        originalPrice: 1350000,
        stock: 3,
      },
      {
        id: "5-hp840",
        name: "Hp 840",
        price: 1130000,
        originalPrice: 1550000,
        stock: 4,
      },
    ],
    mainFeatures: [
      "Mesh back for breathability and comfort",
      "Fabric seat for durability",
      "Adjustable height for personalized fit",
      "Lumbar support for spinal health",
      "Available in multiple colors",
    ],
    keyFeatures: [
      "5-year warranty for peace of mind",
      "Adjustable armrests for added support",
      "Built-in tilt mechanism for easy reclining",
      "Available in various sizes",
      "Ideal for long hours of work",
      "Stylish and professional appearance",
    ],
    whatsInTheBox: [
      "Ergonomic Office Chair",
      "Adjustment Tools",
      "User Manual",
    ],
    createdAt: "2024-01-05T16:45:00Z",
    updatedAt: "2024-01-21T12:00:00Z",
  },
  {
    id: "16",
    name: "Standing Desk Converter",
    description: "Adjustable standing desk converter for healthier work",
    price: 199,
    originalPrice: 249,
    images: [
      "/standing-desk-converter.png",
      "/desk-converter-raised.png",
      "/desk-converter-setup.png",
    ],
    category: "Home & Office",
    subcategory: "Furniture",
    brand: "FlexiDesk",
    stock: 34,
    rating: 4.5,
    reviewCount: 98,
    featured: false,
    tags: ["standing-desk", "adjustable", "ergonomic", "health"],
    specifications: {
      "Height Range": "4.7 - 19.7 inches",
      "Weight Capacity": "35 lbs",
      "Keyboard Tray": "Included",
      Assembly: "No tools required",
    },
    variations: [
      {
        id: "17-standard",
        name: "Standard",
        price: 199,
        stock: 34,
        sku: "FLEXIDESK-STD",
      },
      {
        id: "17-pro",
        name: "Pro",
        price: 249,
        stock: 30,
        sku: "FLEXIDESK-PRO",
      },
    ],
    mainFeatures: [
      "Adjustable height for standing or sitting",
      "Keyboard tray for ergonomic setup",
      "No tools required for assembly",
      "Compact design for easy storage",
      "Available in multiple colors",
    ],
    keyFeatures: [
      "Ideal for promoting healthier work habits",
      "Adjustable height range for personalized fit",
      "Built-in cable management for a tidy workspace",
      "Available in various sizes",
      "Stylish and modern appearance",
      "Easy to install and use",
    ],
    whatsInTheBox: [
      "Standing Desk Converter",
      "Adjustment Tools",
      "User Manual",
    ],
    createdAt: "2024-01-04T11:20:00Z",
    updatedAt: "2024-01-14T13:40:00Z",
  },
  {
    id: "17",
    name: "Vitamin C Serum",
    description:
      "Brightening vitamin C serum for radiant, healthy-looking skin",
    price: 45,
    images: [
      "/vitamin-c-serum-bottle.jpg",
      "/skincare-serum-dropper.png",
      "/vitamin-c-serum-texture.jpg",
    ],
    category: "Health & Beauty",
    subcategory: "Skincare",
    brand: "GlowSkin",
    stock: 73,
    rating: 4.4,
    reviewCount: 203,
    featured: false,
    tags: ["skincare", "vitamin-c", "serum", "brightening"],
    specifications: {
      Concentration: "20% Vitamin C",
      Volume: "30ml",
      "Skin Type": "All Skin Types",
      "Cruelty Free": "Yes",
    },
    variations: [
      { id: "6-30ml", name: "30ml", price: 45, stock: 73, sku: "VITAMINC30ML" },
      { id: "6-60ml", name: "60ml", price: 89, stock: 60, sku: "VITAMINC60ML" },
    ],
    mainFeatures: [
      "20% Vitamin C concentration for powerful brightening",
      "30ml volume for long-lasting use",
      "Suitable for all skin types",
      "Cruelty-free formula",
      "Available in multiple sizes",
    ],
    keyFeatures: [
      "Hydrating formula for nourished skin",
      "Anti-aging properties for youthful appearance",
      "Suitable for daily use",
      "Available in various fragrances",
      "Ideal for sensitive skin",
      "Non-comedogenic formula",
    ],
    whatsInTheBox: ["Vitamin C Serum", "Applicator Dropper", "User Manual"],
    createdAt: "2024-01-14T08:15:00Z",
    updatedAt: "2024-01-23T15:20:00Z",
  },
  {
    id: "18",
    name: "Professional Makeup Brush Set",
    description: "Complete 12-piece makeup brush set with premium bristles",
    price: 89,
    originalPrice: 129,
    images: [
      "/makeup-brush-set.png",
      "/brushes-individual.png",
      "/brush-case.png",
    ],
    category: "Health & Beauty",
    subcategory: "Makeup",
    brand: "BeautyPro",
    stock: 45,
    rating: 4.7,
    reviewCount: 167,
    featured: true,
    tags: ["makeup", "brushes", "professional", "beauty"],
    specifications: {
      "Brush Count": "12 pieces",
      Bristles: "Synthetic",
      Handle: "Wooden",
      Case: "Included",
    },
    variations: [
      {
        id: "18-12brushes",
        name: "12 Brushes",
        price: 89,
        stock: 45,
        sku: "MAKEUPBRUSHSET-12",
      },
      {
        id: "18-24brushes",
        name: "24 Brushes",
        price: 129,
        stock: 40,
        sku: "MAKEUPBRUSHSET-24",
      },
    ],
    mainFeatures: [
      "Complete 12-piece makeup brush set",
      "Premium synthetic bristles for smooth application",
      "Wooden handle for durability and comfort",
      "Included case for easy storage",
      "Available in multiple sizes",
    ],
    keyFeatures: [
      "Ideal for professional makeup artists",
      "Versatile brushes for various makeup techniques",
      "Easy to clean and maintain",
      "Available in various colors",
      "Stylish and elegant design",
      "Built-in storage case for organization",
    ],
    whatsInTheBox: [
      "Professional Makeup Brush Set",
      "Cleaning Cloth",
      "User Manual",
    ],
    createdAt: "2024-01-03T10:30:00Z",
    updatedAt: "2024-01-13T12:45:00Z",
  },
  {
    id: "19",
    name: "Adjustable Dumbbells Set",
    description: "Space-saving adjustable dumbbells for home workouts",
    price: 299,
    originalPrice: 399,
    images: [
      "/adjustable-dumbbells.png",
      "/dumbbells-weights.png",
      "/dumbbells-rack.png",
    ],
    category: "Sports & Outdoors",
    subcategory: "Fitness Equipment",
    brand: "FitHome",
    stock: 16,
    rating: 4.8,
    reviewCount: 234,
    featured: true,
    tags: ["dumbbells", "adjustable", "fitness", "home-gym"],
    specifications: {
      "Weight Range": "5-50 lbs per dumbbell",
      Material: "Cast Iron with Rubber Coating",
      "Space Required": "Minimal",
      Warranty: "2 Years",
    },
    variations: [
      {
        id: "19-5lbs",
        name: "5 lbs",
        price: 299,
        stock: 16,
        sku: "ADUMBBELLS-5",
      },
      {
        id: "19-10lbs",
        name: "10 lbs",
        price: 349,
        stock: 14,
        sku: "ADUMBBELLS-10",
      },
    ],
    mainFeatures: [
      "Adjustable weight range for versatile workouts",
      "Cast Iron construction for durability",
      "Rubber coating for comfortable grip",
      "Minimal space required for easy storage",
      "Available in multiple weights",
    ],
    keyFeatures: [
      "Ideal for home gym setups",
      "Compact design for space-saving",
      "Easy to adjust weights",
      "Available in various colors",
      "Built-in rack for convenient storage",
      "2-year warranty for peace of mind",
    ],
    whatsInTheBox: [
      "Adjustable Dumbbells Set",
      "Adjustment Tools",
      "User Manual",
    ],
    createdAt: "2024-01-02T09:15:00Z",
    updatedAt: "2024-01-12T11:30:00Z",
  },
  {
    id: "20",
    name: "Camping Tent 4-Person",
    description: "Waterproof family camping tent with easy setup",
    price: 149,
    originalPrice: 199,
    images: [
      "/camping-tent-4-person.png",
      "/tent-interior.png",
      "/tent-setup.png",
    ],
    category: "Sports & Outdoors",
    subcategory: "Outdoor Gear",
    brand: "OutdoorLife",
    stock: 27,
    rating: 4.5,
    reviewCount: 156,
    featured: false,
    tags: ["tent", "camping", "waterproof", "family"],
    specifications: {
      Capacity: "4 Person",
      "Floor Area": "64 sq ft",
      "Peak Height": "6 ft",
      "Setup Time": "10 minutes",
    },
    variations: [
      {
        id: "20-4person",
        name: "4 Person",
        price: 149,
        stock: 27,
        sku: "CAMPINGTENT-4P",
      },
      {
        id: "20-6person",
        name: "6 Person",
        price: 199,
        stock: 22,
        sku: "CAMPINGTENT-6P",
      },
    ],
    mainFeatures: [
      "Waterproof design for reliable protection",
      "4-person capacity for family use",
      "64 sq ft floor area for ample space",
      "Easy setup with minimal tools",
      "Available in multiple sizes",
    ],
    keyFeatures: [
      "Ideal for family camping trips",
      "Compact design for easy transportation",
      "Built-in storage pockets for essentials",
      "Available in various colors",
      "Sturdy construction for durability",
      "Easy to clean and maintain",
    ],
    whatsInTheBox: [
      "Camping Tent",
      "Tent Poles",
      "Carabiners",
      "Stakes",
      "Quick Start Guide",
    ],
    createdAt: "2024-01-01T15:45:00Z",
    updatedAt: "2024-01-11T17:20:00Z",
  },
  {
    id: "21",
    name: "Baby Stroller Travel System",
    description: "Complete travel system with car seat and base",
    price: 399,
    originalPrice: 499,
    images: [
      "/baby-stroller-system.png",
      "/stroller-car-seat.png",
      "/stroller-folded.png",
    ],
    category: "Baby Products",
    subcategory: "Baby Gear",
    brand: "SafeRide",
    stock: 19,
    rating: 4.9,
    reviewCount: 278,
    featured: true,
    tags: ["stroller", "car-seat", "travel-system", "safety"],
    specifications: {
      "Age Range": "Birth to 4 years",
      "Weight Limit": "50 lbs",
      "Car Seat": "Included",
      "Safety Rating": "5-Star",
    },
    variations: [
      {
        id: "21-standard",
        name: "Standard",
        price: 399,
        stock: 19,
        sku: "BABYSTROLLER-STD",
      },
      {
        id: "21-pro",
        name: "Pro",
        price: 499,
        stock: 15,
        sku: "BABYSTROLLER-PRO",
      },
    ],
    mainFeatures: [
      "Complete travel system with car seat and base",
      "Suitable for babies from birth to 4 years",
      "50 lbs weight limit for safety",
      "Included car seat for added convenience",
      "Available in multiple sizes",
    ],
    keyFeatures: [
      "Ideal for family travel",
      "Compact design for easy transportation",
      "Built-in storage pockets for essentials",
      "Available in various colors",
      "Sturdy construction for durability",
      "Easy to clean and maintain",
    ],
    whatsInTheBox: [
      "Baby Stroller Travel System",
      "Car Seat",
      "Base",
      "Adjustment Tools",
      "User Manual",
    ],
    createdAt: "2023-12-30T14:20:00Z",
    updatedAt: "2024-01-10T16:35:00Z",
  },
  {
    id: "22",
    name: "Educational Building Blocks",
    description: "Colorful building blocks for developing motor skills",
    price: 39,
    originalPrice: 49,
    images: ["/building-blocks.png", "/blocks-colors.png", "/blocks-play.png"],
    category: "Baby Products",
    subcategory: "Toys",
    brand: "LearnPlay",
    stock: 78,
    rating: 4.6,
    reviewCount: 189,
    featured: false,
    tags: ["toys", "educational", "building", "motor-skills"],
    specifications: {
      "Age Range": "12 months+",
      "Piece Count": "50 blocks",
      Material: "BPA-Free Plastic",
      "Safety Certified": "Yes",
    },
    variations: [
      {
        id: "22-50blocks",
        name: "50 Blocks",
        price: 39,
        stock: 78,
        sku: "BUILDINGBLOCKS-50",
      },
      {
        id: "22-100blocks",
        name: "100 Blocks",
        price: 49,
        stock: 70,
        sku: "BUILDINGBLOCKS-100",
      },
    ],
    mainFeatures: [
      "Colorful building blocks for engaging play",
      "50-piece set for developing motor skills",
      "BPA-Free plastic for safety",
      "Safety certified for peace of mind",
      "Available in multiple sizes",
    ],
    keyFeatures: [
      "Ideal for early childhood development",
      "Encourages creativity and problem-solving",
      "Compact design for easy storage",
      "Available in various colors",
      "Sturdy construction for durability",
      "Easy to clean and maintain",
    ],
    whatsInTheBox: [
      "Educational Building Blocks",
      "Storage Container",
      "User Manual",
    ],
    createdAt: "2023-12-29T12:10:00Z",
    updatedAt: "2024-01-09T14:25:00Z",
  },
];

export const banners: Banner[] = [
  {
    id: "1",
    title: "New Year Sale",
    subtitle: "Up to 50% off on selected items",
    image: "/new-year-sale-banner.jpg",
    link: "/promotions/new-year-sale",
    buttonText: "Shop Now",
    active: true,
    order: 1,
  },
  {
    id: "2",
    title: "Latest Electronics",
    subtitle: "Discover cutting-edge technology",
    image: "/electronics-banner.png",
    link: "/categories/electronics",
    buttonText: "Explore",
    active: true,
    order: 2,
  },
  {
    id: "3",
    title: "Fashion Forward",
    subtitle: "Trending styles for every season",
    image: "/fashion-banner.png",
    link: "/categories/fashion",
    buttonText: "Shop Fashion",
    active: true,
    order: 3,
  },
];

export const promotions: Promotion[] = [
  {
    id: "1",
    title: "New Year Mega Sale",
    description: "Get up to 50% off on electronics and fashion items",
    discountType: "percentage",
    discountValue: 50,
    code: "NEWYEAR50",
    startDate: "2024-01-01T00:00:00Z",
    endDate: "2024-01-31T23:59:59Z",
    active: true,
    applicableCategories: ["Phones and Tablets", "Computers", "Fashion"],
  },
  {
    id: "2",
    title: "Free Shipping Weekend",
    description: "Free shipping on all orders above Ugx 20,000",
    discountType: "fixed",
    discountValue: 0,
    startDate: "2024-01-26T00:00:00Z",
    endDate: "2024-01-28T23:59:59Z",
    active: true,
  },
];

export const reviews: Review[] = [
  {
    id: "1",
    productId: "1",
    customerName: "John Smith",
    customerEmail: "john@example.com",
    rating: 5,
    title: "Amazing phone!",
    comment:
      "The iPhone 15 Pro Max exceeded my expectations. The camera quality is incredible and the battery life is outstanding.",
    verified: true,
    helpful: 12,
    createdAt: "2024-01-20T14:30:00Z",
  },
  {
    id: "2",
    productId: "2",
    customerName: "Sarah Johnson",
    customerEmail: "sarah@example.com",
    rating: 5,
    title: "Perfect for work",
    comment:
      "This MacBook Pro handles all my design work effortlessly. The display is stunning and performance is top-notch.",
    verified: true,
    helpful: 8,
    createdAt: "2024-01-18T16:45:00Z",
  },
  {
    id: "3",
    productId: "3",
    customerName: "Mike Davis",
    customerEmail: "mike@example.com",
    rating: 4,
    title: "Great noise cancellation",
    comment:
      "These headphones are fantastic for travel. The noise cancellation works really well on flights.",
    verified: true,
    helpful: 15,
    createdAt: "2024-01-22T13:15:00Z",
  },
];

export const testimonials: Testimonial[] = [
  {
    id: "1",
    customerName: "Emily Chen",
    customerImage: "/customer-profile-woman.jpg",
    rating: 5,
    comment:
      "Excellent service and fast delivery. The products are exactly as described and the quality is outstanding.",
    location: "New York, NY",
    verified: true,
    featured: true,
    createdAt: "2024-01-15T10:00:00Z",
  },
  {
    id: "2",
    customerName: "David Wilson",
    customerImage: "/customer-profile-man.jpg",
    rating: 5,
    comment:
      "I've been shopping here for months and never had a bad experience. Great customer support and competitive prices.",
    location: "Los Angeles, CA",
    verified: true,
    featured: true,
    createdAt: "2024-01-12T11:30:00Z",
  },
  {
    id: "3",
    customerName: "Lisa Rodriguez",
    customerImage: "/customer-profile-woman-hispanic.jpg",
    rating: 5,
    comment:
      "The website is easy to navigate and the checkout process is smooth. Highly recommend this store!",
    location: "Miami, FL",
    verified: true,
    featured: true,
    createdAt: "2024-01-10T09:00:00Z",
  },
];
